### ISSUE TITLE
[BUG] pima_diabetes example fails to register

### ISSUE THREAD

**Issue by tekumara** [flyteorg/flyte#1318]
**Describe the bug**
```
$ SANDBOX=1 make -C cookbook/case_studies/ml_training/pima_diabetes register
Tagged Image: 
flytecookbook:pima_diabetes-ff4e179abe231d65fe06f24a181f96ad737d40ee
[+] Building 2.4s (20/20) FINISHED                                                                                                          
 => [internal] load build definition from Dockerfile                                                                                   0.0s
 => => transferring dockerfile: 37B                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                      0.0s
 => => transferring context: 2B                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/ubuntu:focal                                                                        2.2s
 => [ 1/15] FROM docker.io/library/ubuntu:focal@sha256:82becede498899ec668628e7cb0ad87b6e1c371cb8a1e597d83a47fac21d6af3                0.0s
 => [internal] load build context                                                                                                      0.0s
 => => transferring context: 658B                                                                                                      0.0s
 => CACHED [ 2/15] WORKDIR /root                                                                                                       0.0s
 => CACHED [ 3/15] RUN :     && apt-get update     && apt install -y software-properties-common     && add-apt-repository ppa:deadsna  0.0s
 => CACHED [ 4/15] RUN :     && apt-get update     && apt-get install -y python3.8 python3-pip python3-venv make build-essential libs  0.0s
 => CACHED [ 5/15] RUN apt-get update && apt-get install -y libsm6 libxext6 libxrender-dev ffmpeg                                      0.0s
 => CACHED [ 6/15] RUN pip3 install awscli                                                                                             0.0s
 => CACHED [ 7/15] RUN python3.8 -m venv /opt/venv                                                                                     0.0s
 => CACHED [ 8/15] RUN /opt/venv/bin/pip install wheel                                                                                 0.0s
 => CACHED [ 9/15] COPY pima_diabetes/requirements.txt /root                                                                           0.0s
 => CACHED [10/15] RUN /opt/venv/bin/pip install -r /root/requirements.txt                                                             0.0s
 => CACHED [11/15] COPY in_container.mk /root/Makefile                                                                                 0.0s
 => CACHED [12/15] COPY pima_diabetes/sandbox.config /root                                                                             0.0s
 => CACHED [13/15] COPY pima_diabetes/ /root/pima_diabetes/                                                                            0.0s
 => CACHED [14/15] RUN cp /opt/venv/bin/flytekit_venv /usr/local/bin/                                                                  0.0s
 => CACHED [15/15] RUN chmod a+x /usr/local/bin/flytekit_venv                                                                          0.0s
 => exporting to image                                                                                                                 0.0s
 => => exporting layers                                                                                                                0.0s
 => => writing image sha256:d3346365711793716e2e1554f5d9d620c388891f106a117b7ead168a61a0b288                                           0.0s
 => => naming to docker.io/library/flytecookbook:pima_diabetes-ff4e179abe231d65fe06f24a181f96ad737d40ee                                0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
ff4e179abe231d65fe06f24a181f96ad737d40ee
/Users/tekumara/code3/flytesnacks/cookbook/case_studies/ml_training/pima_diabetes
Using configuration file at /root/sandbox.config
Flyte Admin URL None
Serializing Flyte elements with image flytecookbook:pima_diabetes-ff4e179abe231d65fe06f24a181f96ad737d40ee
Writing output to /tmp/output
DEBUG:root:             [2] Pushing context - execute, branch[False], StackOrigin(serialize_all, 219, /opt/venv/lib/python3.8/site-packages/flytekit/clis/sdk_in_container/serialize.py)
{"asctime": "2021-08-07 10:50:16,126", "name": "flytekit", "levelname": "DEBUG", "message": "Task returns unnamed typing.Tuple typing.Tuple[flytekit.types.schema.types.FlyteSchema.__class_getitem__.<locals>._TypedSchema, flytekit.types.schema.types.FlyteSchema.__class_getitem__.<locals>._TypedSchema, flytekit.types.schema.types.FlyteSchema.__class_getitem__.<locals>._TypedSchema, flytekit.types.schema.types.FlyteSchema.__class_getitem__.<locals>._TypedSchema]"}
DEBUG:flytekit:Task returns unnamed typing.Tuple typing.Tuple[flytekit.types.schema.types.FlyteSchema.__class_getitem__.<locals>._TypedSchema, flytekit.types.schema.types.FlyteSchema.__class_getitem__.<locals>._TypedSchema, flytekit.types.schema.types.FlyteSchema.__class_getitem__.<locals>._TypedSchema, flytekit.types.schema.types.FlyteSchema.__class_getitem__.<locals>._TypedSchema]
{"asctime": "2021-08-07 10:50:16,127", "name": "flytekit", "levelname": "DEBUG", "message": "Task returns named tuple <class 'pima_diabetes.diabetes.Model'>"}
DEBUG:flytekit:Task returns named tuple <class 'pima_diabetes.diabetes.Model'>
{"asctime": "2021-08-07 10:50:16,129", "name": "flytekit", "levelname": "DEBUG", "message": "Task returns unnamed native tuple <class 'flytekit.types.schema.types.FlyteSchema.__class_getitem__.<locals>._TypedSchema'>"}
DEBUG:flytekit:Task returns unnamed native tuple <class 'flytekit.types.schema.types.FlyteSchema.__class_getitem__.<locals>._TypedSchema'>
{"asctime": "2021-08-07 10:50:16,129", "name": "flytekit", "levelname": "DEBUG", "message": "Task returns unnamed native tuple <class 'float'>"}
DEBUG:flytekit:Task returns unnamed native tuple <class 'float'>
{"asctime": "2021-08-07 10:50:16,130", "name": "flytekit", "levelname": "DEBUG", "message": "Task returns named tuple <class 'pima_diabetes.diabetes.WorkflowOutputs'>"}
DEBUG:flytekit:Task returns named tuple <class 'pima_diabetes.diabetes.WorkflowOutputs'>
DEBUG:root:                     [3] Pushing context - compile, branch[False], StackOrigin(compile, 665, /opt/venv/lib/python3.8/site-packages/flytekit/core/workflow.py)
DEBUG:root:                     [3] Popping context - compile, branch[False], StackOrigin(compile, 665, /opt/venv/lib/python3.8/site-packages/flytekit/core/workflow.py)
No images specified, will use the default image
Found 5 tasks/workflows
DEBUG:root:Looking for LHS for <flytekit.core.python_auto_container.DefaultTaskResolver object at 0x7f9fa9b79d30> from flytekit.core.python_auto_container
DEBUG:root:Found LHS for <flytekit.core.python_auto_container.DefaultTaskResolver object at 0x7f9fa9b79d30>, default_task_resolver
  Packaging pima_diabetes.diabetes.split_traintest_dataset -> 0_pima_diabetes.diabetes.split_traintest_dataset_1.pb
  Packaging pima_diabetes.diabetes.fit -> 1_pima_diabetes.diabetes.fit_1.pb
  Packaging pima_diabetes.diabetes.predict -> 2_pima_diabetes.diabetes.predict_1.pb
  Packaging pima_diabetes.diabetes.score -> 3_pima_diabetes.diabetes.score_1.pb
  Packaging pima_diabetes.diabetes.diabetes_xgboost_model -> 4_pima_diabetes.diabetes.diabetes_xgboost_model_2.pb
  Packaging pima_diabetes.diabetes.diabetes_xgboost_model -> 5_pima_diabetes.diabetes.diabetes_xgboost_model_3.pb
Successfully serialized 6 flyte objects
DEBUG:root:             [2] Popping context - execute, branch[False], StackOrigin(serialize_all, 219, /opt/venv/lib/python3.8/site-packages/flytekit/clis/sdk_in_container/serialize.py)
Config file not found at default location, relying on environment variables instead.
                        To setup your config file run 'flyte-cli setup-config'
Welcome to Flyte CLI! Version: 0.20.0
Parsing files...
  /tmp/output/0_pima_diabetes.diabetes.split_traintest_dataset_1.pb
  /tmp/output/1_pima_diabetes.diabetes.fit_1.pb
  /tmp/output/2_pima_diabetes.diabetes.predict_1.pb
  /tmp/output/3_pima_diabetes.diabetes.score_1.pb
  /tmp/output/4_pima_diabetes.diabetes.diabetes_xgboost_model_2.pb
  /tmp/output/5_pima_diabetes.diabetes.diabetes_xgboost_model_3.pb
Registering resource_type: TASK
project: "flytesnacks"
domain: "development"
name: "pima_diabetes.diabetes.split_traintest_dataset"
version: "ff4e179abe231d65fe06f24a181f96ad737d40ee"

Skipping because already registered resource_type: TASK
project: "flytesnacks"
domain: "development"
name: "pima_diabetes.diabetes.split_traintest_dataset"
version: "ff4e179abe231d65fe06f24a181f96ad737d40ee"

Registering resource_type: TASK
project: "flytesnacks"
domain: "development"
name: "pima_diabetes.diabetes.fit"
version: "ff4e179abe231d65fe06f24a181f96ad737d40ee"

Skipping because already registered resource_type: TASK
project: "flytesnacks"
domain: "development"
name: "pima_diabetes.diabetes.fit"
version: "ff4e179abe231d65fe06f24a181f96ad737d40ee"

Registering resource_type: TASK
project: "flytesnacks"
domain: "development"
name: "pima_diabetes.diabetes.predict"
version: "ff4e179abe231d65fe06f24a181f96ad737d40ee"

Skipping because already registered resource_type: TASK
project: "flytesnacks"
domain: "development"
name: "pima_diabetes.diabetes.predict"
version: "ff4e179abe231d65fe06f24a181f96ad737d40ee"

Registering resource_type: TASK
project: "flytesnacks"
domain: "development"
name: "pima_diabetes.diabetes.score"
version: "ff4e179abe231d65fe06f24a181f96ad737d40ee"

Skipping because already registered resource_type: TASK
project: "flytesnacks"
domain: "development"
name: "pima_diabetes.diabetes.score"
version: "ff4e179abe231d65fe06f24a181f96ad737d40ee"

Registering resource_type: WORKFLOW
project: "flytesnacks"
domain: "development"
name: "pima_diabetes.diabetes.diabetes_xgboost_model"
version: "ff4e179abe231d65fe06f24a181f96ad737d40ee"

Traceback (most recent call last):
  File "/opt/venv/bin/flyte-cli", line 8, in <module>
    sys.exit(_flyte_cli())
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/flytekit/clis/flyte_cli/main.py", line 1882, in register_files
    _extract_and_register(host, insecure, project, domain, version, files, patches)
  File "/opt/venv/lib/python3.8/site-packages/flytekit/clis/flyte_cli/main.py", line 1817, in _extract_and_register
    client.raw.create_workflow(_workflow_pb2.WorkflowCreateRequest(id=id, spec=flyte_entity))
  File "/opt/venv/lib/python3.8/site-packages/flytekit/clients/raw.py", line 131, in handler
    return fn(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/flytekit/clients/raw.py", line 170, in handler
    raise e
  File "/opt/venv/lib/python3.8/site-packages/flytekit/clients/raw.py", line 163, in handler
    fn(self, create_request)
  File "/opt/venv/lib/python3.8/site-packages/flytekit/clients/raw.py", line 342, in create_workflow
    return self._stub.CreateWorkflow(workflow_create_request, metadata=self._metadata)
  File "/opt/venv/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/venv/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "failed to compile workflow for [resource_type:WORKFLOW project:"flytesnacks" domain:"development" name:"pima_diabetes.diabetes.diabetes_xgboost_model" version:"ff4e179abe231d65fe06f24a181f96ad737d40ee" ] with err failed to compile workflow with err Collected Errors: 2
        Error 0: Code: MismatchingTypes, Node Id: n0, Description: Variable [dataset] (type [blob:<format:"csv" > ]) doesn't match expected type [blob:<> ].
        Error 1: Code: ParameterNotBound, Node Id: n0, Description: Parameter not bound [dataset].
"
        debug_error_string = "{"created":"@1628333417.146930007","description":"Error received from peer ipv4:127.0.0.1:30081","file":"src/core/lib/surface/call.cc","file_line":1066,"grpc_message":"failed to compile workflow for [resource_type:WORKFLOW project:"flytesnacks" domain:"development" name:"pima_diabetes.diabetes.diabetes_xgboost_model" version:"ff4e179abe231d65fe06f24a181f96ad737d40ee" ] with err failed to compile workflow with err Collected Errors: 2\n\tError 0: Code: MismatchingTypes, Node Id: n0, Description: Variable [dataset] (type [blob:<format:"csv" > ]) doesn't match expected type [blob:<> ].\n\tError 1: Code: ParameterNotBound, Node Id: n0, Description: Parameter not bound [dataset].\n","grpc_status":13}"
>
make: *** [Makefile:16: register] Error 1
make: *** [register] Error 2
```

flytesnacks commit ff4e179 (v0.2.155)

**Comment by tekumara** [comment]
Ah this was because of a incorrect change I made, and not something in the original code.
