### ISSUE TITLE
[BUG] flytectl get execution details - nil pointer dereference

### ISSUE THREAD

**Issue by tekumara** [flyteorg/flyte#1320]
```
❯ flytectl get execution --project flytesnacks --domain development fad4b79cb511b44acb78
 ---------------------- ----------------------------------------------- ------------- --------- -------------------------------- -------------- -------------------- --------------------
| NAME                 | LAUNCH PLAN NAME                              | TYPE        | PHASE   | STARTED                        | ELAPSED TIME | ABORT DATA (TRUNC) | ERROR DATA (TRUNC) |
 ---------------------- ----------------------------------------------- ------------- --------- -------------------------------- -------------- -------------------- --------------------
| fad4b79cb511b44acb78 | pima_diabetes.diabetes.diabetes_xgboost_model | LAUNCH_PLAN | RUNNING | 2021-08-07T11:44:03.655156532Z |              |                    |                    |
 ---------------------- ----------------------------------------------- ------------- --------- -------------------------------- -------------- -------------------- --------------------
1 rows

❯ flytectl get execution --project flytesnacks --domain development fad4b79cb511b44acb78 --details
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d576e5]

goroutine 1 [running]:
github.com/flyteorg/flytectl/cmd/get.extractLiteralMap(0x0, 0xc00077e120, 0x0, 0x0)
	/home/runner/work/flytectl/flytectl/cmd/get/node_execution.go:263 +0x45
github.com/flyteorg/flytectl/cmd/get.getNodeExecDetailsInt(0x23d3ec0, 0xc000044078, 0x7ffeefbff581, 0xb, 0x7ffeefbff596, 0xb, 0x7ffeefbff5a2, 0x14, 0x0, 0x0, ...)
	/home/runner/work/flytectl/flytectl/cmd/get/node_execution.go:178 +0x650
github.com/flyteorg/flytectl/cmd/get.getExecutionDetails(0x23d3ec0, 0xc000044078, 0x7ffeefbff581, 0xb, 0x7ffeefbff596, 0xb, 0x7ffeefbff5a2, 0x14, 0x0, 0x0, ...)
	/home/runner/work/flytectl/flytectl/cmd/get/node_execution.go:107 +0x158
github.com/flyteorg/flytectl/cmd/get.getExecutionFunc(0x23d3ec0, 0xc000044078, 0xc0007385a0, 0x1, 0x6, 0x23ec740, 0xc00000ee50, 0x23e5d40, 0xc000143930, 0x23c85c0, ...)
	/home/runner/work/flytectl/flytectl/cmd/get/execution.go:119 +0x418
github.com/flyteorg/flytectl/cmd/core.generateCommandFunc.func1(0xc000722c80, 0xc0007385a0, 0x1, 0x6, 0x0, 0x0)
	/home/runner/work/flytectl/flytectl/cmd/core/cmd.go:69 +0x4b8
github.com/spf13/cobra.(*Command).execute(0xc000722c80, 0xc000738540, 0x6, 0x6, 0xc000722c80, 0xc000738540)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000553400, 0xc0003036b0, 0xc0004bff48, 0x10454aa)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/flyteorg/flytectl/cmd.ExecuteCmd(0xc0004bff78, 0x1006005)
	/home/runner/work/flytectl/flytectl/cmd/root.go:130 +0x2a
main.main()
	/home/runner/work/flytectl/flytectl/main.go:12 +0x26
```

```
❯ flytectl version
A newer version of flytectl is available [v0.2.25] Please upgrade using - https://docs.flyte.org/projects/flytectl/en/latest/index.html
{
  "App": "flytectl",
  "Build": "51877cb",
  "Version": "0.2.25",
  "BuildTime": "2021-08-07 21:54:19.636533 +1000 AEST m=+0.022846802"
}{
  "App": "controlPlane",
  "Build": "0720cf4",
  "Version": "v0.6.16",
  "BuildTime": "2021-08-07 11:06:43.87794724 +0000 UTC m=+0.050774587"
}
```

**Comment by kumare3** [comment]
Cc @pmahindrakar-oss 
I think this is a transitional npe. Still a bug

**Comment by evalsocket** [comment]
@tekumara @kumare3 i am ware about the issue. Currently we didn't support some data types in flytectl that's it is failing while retrieving the input and output of a execution

**Comment by evalsocket** [comment]
Related https://github.com/flyteorg/flyte/issues/1314

**Comment by mayitbeegh** [comment]
Fixed in https://github.com/flyteorg/flytectl/pull/176/files
