### ISSUE TITLE
[BUG] flytectl get launchplan - panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by tekumara** [flyteorg/flyte#1341]
**Describe the bug**

```
flytectl get launchplan -p flyteexamples -d development aircraft.02_etl_flow.main --execFile exec.yaml
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/flyteorg/flytectl/pkg/printer.FormatParameterDescriptions(0x0)
        /home/runner/work/flytectl/flytectl/pkg/printer/printer.go:216 +0x39f
github.com/flyteorg/flytectl/cmd/get.LaunchplanToTableProtoMessages(0xc00040a3d8, 0x1, 0x1, 0xb, 0x2196f63, 0x5)
        /home/runner/work/flytectl/flytectl/cmd/get/launch_plan.go:133 +0x1c8
github.com/flyteorg/flytectl/cmd/get.getLaunchPlanFunc(0x23d3f60, 0xc0000b8000, 0xc000267ab0, 0x1, 0x7, 0x23ec7e0, 0xc00040a170, 0x23e5de0, 0xc00064d5e0, 0x23c8660, ...)
        /home/runner/work/flytectl/flytectl/cmd/get/launch_plan.go:158 +0x390
github.com/flyteorg/flytectl/cmd/core.generateCommandFunc.func1(0xc00037fb80, 0xc000267ab0, 0x1, 0x7, 0x0, 0x0)
        /home/runner/work/flytectl/flytectl/cmd/core/cmd.go:69 +0x4b8
github.com/spf13/cobra.(*Command).execute(0xc00037fb80, 0xc000267a40, 0x7, 0x7, 0xc00037fb80, 0xc000267a40)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000875400, 0xc0002340f0, 0xc0004bff48, 0x10454aa)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/flyteorg/flytectl/cmd.ExecuteCmd(0xc0004bff78, 0x1006005)
        /home/runner/work/flytectl/flytectl/cmd/root.go:130 +0x2a
main.main()
        /home/runner/work/flytectl/flytectl/main.go:12 +0x26
 ```

```
flytectl version  
A newer version of flytectl is available [v0.2.26] Please upgrade using - https://docs.flyte.org/projects/flytectl/en/latest/index.html
{
  "App": "flytectl",
  "Build": "c34698f",
  "Version": "0.2.26",
  "BuildTime": "2021-08-15 19:45:35.853086 +1000 AEST m=+0.020480229"
}{
  "App": "controlPlane",
  "Build": "0720cf4",
  "Version": "v0.6.16",
  "BuildTime": "2021-08-15 07:49:45.082479 +0000 UTC m=+0.038415201"
}
```

**Comment by tekumara** [comment]
This is for workflow that has no inputs or outputs:

```
Config file not found at default location, relying on environment variables instead.
                        To setup your config file run 'flyte-cli setup-config'
Welcome to Flyte CLI! Version: 0.21.3
{
  "template": {
    "id": {
      "resourceType": "WORKFLOW",
      "project": "{{ registration.project }}",
      "domain": "{{ registration.domain }}",
      "name": "aircraft.02_etl_flow.main",
      "version": "{{ registration.version }}"
    },
    "metadata": {},
    "interface": {
      "inputs": {},
      "outputs": {}
    },
    "nodes": [
      {
        "id": "n0",
        "metadata": {
          "name": "flytekit.core.python_function_task.aircraft.02_etl_flow.extract_reference_data",
          "retries": {}
        },
        "taskNode": {
          "referenceId": {
            "resourceType": "TASK",
            "project": "{{ registration.project }}",
            "domain": "{{ registration.domain }}",
            "name": "aircraft.02_etl_flow.extract_reference_data",
            "version": "{{ registration.version }}"
          },
          "overrides": {}
        }
      },
      {
        "id": "n1",
        "metadata": {
          "name": "flytekit.core.python_function_task.aircraft.02_etl_flow.extract_live_data",
          "retries": {}
        },
        "taskNode": {
          "referenceId": {
            "resourceType": "TASK",
            "project": "{{ registration.project }}",
            "domain": "{{ registration.domain }}",
            "name": "aircraft.02_etl_flow.extract_live_data",
            "version": "{{ registration.version }}"
          },
          "overrides": {}
        }
      },
      {
        "id": "n2",
        "metadata": {
          "name": "flytekit.core.python_function_task.aircraft.02_etl_flow.transform",
          "retries": {}
        },
        "inputs": [
          {
            "var": "airlines",
            "binding": {
              "promise": {
                "nodeId": "n0",
                "var": "airlines"
              }
            }
          },
          {
            "var": "raw_aircraft_data",
            "binding": {
              "promise": {
                "nodeId": "n1",
                "var": "o0"
              }
            }
          }
        ],
        "upstreamNodeIds": [
          "n1",
          "n0"
        ],
        "taskNode": {
          "referenceId": {
            "resourceType": "TASK",
            "project": "{{ registration.project }}",
            "domain": "{{ registration.domain }}",
            "name": "aircraft.02_etl_flow.transform",
            "version": "{{ registration.version }}"
          },
          "overrides": {}
        }
      },
      {
        "id": "n3",
        "metadata": {
          "name": "flytekit.core.python_function_task.aircraft.02_etl_flow.load_reference_data",
          "retries": {}
        },
        "inputs": [
          {
            "var": "airlines",
            "binding": {
              "promise": {
                "nodeId": "n0",
                "var": "airlines"
              }
            }
          },
          {
            "var": "airports",
            "binding": {
              "promise": {
                "nodeId": "n0",
                "var": "airports"
              }
            }
          },
          {
            "var": "routes",
            "binding": {
              "promise": {
                "nodeId": "n0",
                "var": "routes"
              }
            }
          }
        ],
        "upstreamNodeIds": [
          "n0"
        ],
        "taskNode": {
          "referenceId": {
            "resourceType": "TASK",
            "project": "{{ registration.project }}",
            "domain": "{{ registration.domain }}",
            "name": "aircraft.02_etl_flow.load_reference_data",
            "version": "{{ registration.version }}"
          },
          "overrides": {}
        }
      },
      {
        "id": "n4",
        "metadata": {
          "name": "flytekit.core.python_function_task.aircraft.02_etl_flow.load_live_data",
          "retries": {}
        },
        "inputs": [
          {
            "var": "live_aircraft_data",
            "binding": {
              "promise": {
                "nodeId": "n2",
                "var": "o0"
              }
            }
          }
        ],
        "upstreamNodeIds": [
          "n2"
        ],
        "taskNode": {
          "referenceId": {
            "resourceType": "TASK",
            "project": "{{ registration.project }}",
            "domain": "{{ registration.domain }}",
            "name": "aircraft.02_etl_flow.load_live_data",
            "version": "{{ registration.version }}"
          },
          "overrides": {}
        }
      }
    ],
    "metadataDefaults": {}
  }
}
```

**Comment by kumare3** [comment]
cc @pmahindrakar-oss

**Comment by pmahindrakar-oss** [comment]
@tekumara this should be fixed now . Can you try `flytectl upgrade` to get the latest and check if you still see this issue.
https://github.com/flyteorg/flytectl/pull/168

**Comment by pmahindrakar-oss** [comment]
Following was the PR which fixed the trace https://github.com/flyteorg/flytectl/pull/174
Closing the issue
