### ISSUE TITLE
[BUG] Fast Register command is not working with flyte-cli

### ISSUE THREAD

**Issue by evalsocket** [flyteorg/flyte#1436]
**Describe the bug**
In flytesnacks fast register make target is not working. Issue with flyte-cli 
```
.PHONY: fast_register
fast_register: _requires-sandbox-up  ## Fast register Flyte cookbook workflows
	$(call LOG,Fast registering example workflows in cookbook/$(EXAMPLES_MODULE))
	$(call RUN_IN_SANDBOX,make -C cookbook/$(EXAMPLES_MODULE) fast_register)


ERROR:root:Exception when trying to execute ['aws', '--endpoint-url', 'http://localhost:30084', 's3', 'cp', '--acl', 'bucket-owner-full-control', '/tmp/output/fastb6a91fe4ecad6ab080702654081de5f2.tar.gz', 's3://my-s3-bucket/fast/fastb6a91fe4ecad6ab080702654081de5f2.tar.gz'], reason: Called process exited with error code: 1.  Stderr dump:

b'upload failed: ../tmp/output/fastb6a91fe4ecad6ab080702654081de5f2.tar.gz to s3://my-s3-bucket/fast/fastb6a91fe4ecad6ab080702654081de5f2.tar.gz An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist\n'
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/flytekit/interfaces/data/data_proxy.py", line 154, in put_data
    proxy.upload(local_path, remote_path)
  File "/opt/venv/lib/python3.8/site-packages/flytekit/interfaces/data/s3/s3proxy.py", line 175, in upload
    return _update_cmd_config_and_execute(cmd)
  File "/opt/venv/lib/python3.8/site-packages/flytekit/interfaces/data/s3/s3proxy.py", line 44, in _update_cmd_config_and_execute
    return _subprocess.check_call(cmd, env=env)
  File "/opt/venv/lib/python3.8/site-packages/flytekit/tools/subprocess.py", line 25, in check_call
```
Full Logs : https://github.com/flyteorg/flytesnacks/runs/3518558381#step:5:1201

**Expected behavior**

**[Optional] Additional context**
***To Reproduce***
1. 
2. 

***Screenshots***

**Comment by evalsocket** [comment]
Related to helm sandbox.  flyte-cli needs the bucket name, it will not create a bucket if that does not exist.
