### ISSUE TITLE
[BUG] Error message is not informative enough

### ISSUE THREAD

**Issue by vsbus** [flyteorg/flyte#1468]
**Describe the bug**
slack discussion: https://flyte-org.slack.com/archives/CREL4QVAQ/p1631553952129000

In the task
```
@flytekit.task(
    cache=False,
    retries=DEFAULT_TASK_RETRIES,
    requests=flytekit.Resources(mem="4G", cpu="1"),
)
def fuse_tracks_task(
    input_tracks: List[FlyteFile],
) -> FlyteFile:
    working_dir = Path(flytekit.current_context().working_directory)
    fused_output = str(fusion_result_path(workspace=working_dir))
    tracks_local_paths = []
    for tracks in input_tracks:
        tracks_local_paths.append(os.fspath(tracks))
    call_scene_reconstruction_binary(
        SceneCommand.FUSE_TRACKS.value,
        "fuse-tracks",
        *tracks_local_paths,
        output=fused_output,
    )
    return FlyteFile(path=fused_output)
```

We see failures sometimes. Probably when `fused_output` file doesn't exist. The error displayed in UI is:
```
[2/2] currentAttempt done. Last Error: USER::Traceback (most recent call last):

      File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.8/site-packages/flytekit/common/exceptions/scopes.py", line 165, in system_entry_point
        return wrapped(*args, **kwargs)
      File "/root/.local/share/virtualenvs/root-BuDEOXnJ/lib/python3.8/site-packages/flytekit/core/base_task.py", line 546, in dispatch_execute
        raise AssertionError(f"failed to convert return value for var {k}") from e

Message:

    failed to convert return value for var o0

SYSTEM ERROR! Contact platform administrators.
```

**Expected behavior**
It would help to have more information in the error message about what actually went wrong. E.g.
```
failed to convert return value for var o0: file /abc/xyz.foo doesn't exist
```
or
```
failed to convert return value for var o0: file /abc/xyz.foo exist but empty
```

**[Optional] Additional context**
***To Reproduce***
1. 
2. 

***Screenshots***

**Comment by sushrut111** [comment]
I would love to take this up

**Comment by kumare3** [comment]
@sushrut111 please join the slack channel on Flyte slack and someone will assist

**Comment by samhita-alla** [comment]
Here's the link to join Slack: https://docs.google.com/forms/d/e/1FAIpQLScWPJZncyL-bBCWbuQ9HWuMzA8-r2RJc__CSWJoAYUQADN-BQ/viewform.
