### ISSUE TITLE
flyte-cli setup-config throws JSONDecodeError

### ISSUE THREAD

**Issue by giordyb** [flyteorg/flyte#163]
Hi,

When I try to run 
`flyte-cli setup-config -h localhost:30081 -i`

I get the following error: 

`elcome to Flyte CLI! Version: 0.4.4
Traceback (most recent call last):
  File "/Users/biagio/opt/anaconda3/envs/yolo_train_framework/bin/flyte-cli", line 8, in <module>
    sys.exit(_flyte_cli())
  File "/Users/biagio/opt/anaconda3/envs/yolo_train_framework/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/biagio/opt/anaconda3/envs/yolo_train_framework/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/biagio/opt/anaconda3/envs/yolo_train_framework/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/biagio/opt/anaconda3/envs/yolo_train_framework/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/biagio/opt/anaconda3/envs/yolo_train_framework/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/biagio/opt/anaconda3/envs/yolo_train_framework/lib/python3.6/site-packages/flytekit/clis/flyte_cli/main.py", line 1522, in setup_config
    data = response.json()
  File "/Users/biagio/opt/anaconda3/envs/yolo_train_framework/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/biagio/opt/anaconda3/envs/yolo_train_framework/lib/python3.6/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/Users/biagio/opt/anaconda3/envs/yolo_train_framework/lib/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Users/biagio/opt/anaconda3/envs/yolo_train_framework/lib/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

I'm running flyte-cli on MacOS with the sandbox setup on Docker for Mac with K8s

**Comment by kumare3** [comment]
@giordyb thank you for opening the issue, we will get this resolved soon. Also, I think you are on our slack channel, we should be able to unblock you. But, I will definitely make it a point to update the issue so that we can keep track and educate other new members better.

**Comment by EngHabu** [comment]
@wild-endeavor has this been resolved?

**Comment by wild-endeavor** [comment]
No, this is an admin change we'll need to make.  Currently the endpoint only works I think when auth is enabled on the admin service.  The admin auth bits need some tlc in the coming weeks.
