### ISSUE TITLE
[BUG] pyflyte init command results in a stack trace  

### ISSUE THREAD

**Issue by palchicz** [flyteorg/flyte#1948]
### Describe the bug

Invocation of  `pyflyte init <new_project_name>` results in a stack trace. The exact error is `AttributeError: module 'flyteidl.core.types_pb2' has no attribute 'EnumType'

### Expected behavior

 I expected `pyflyte init <new_project_name>` to produce a new directory with name <new_project_name> with a sample workflow. 

### Additional context to reproduce

I was following the [getting started guide](https://docs.flyte.org/en/latest/getting_started.html#gettingstarted-implement) with the aim of setting up a fresh install of flyte.  Starting with a fresh virtual environment (using pyenv-virtualenv) with python 3.8.7

```bash
> pyenv virtualenv 3.8.7 flyte_virtual_env
> pyenv activate flyte_virtual_env
> (flyte_virtual_env) pip install flytekit --upgrade
...  # success

> (flyte_virtual_env) pyflyte init new_project
... # failure
```

The failure is the following stack trace
```log
Traceback (most recent call last):
  File "/home/.pyenv/versions/flyte_virtual_env/bin/pyflyte", line 5, in <module>
    from flytekit.clis.sdk_in_container.pyflyte import main
  File "/home/.pyenv/versions/3.8.7/envs/flyte_virtual_env/lib/python3.8/site-packages/flytekit/__init__.py", line 164, in <module>
    from flytekit.core.base_sql_task import SQLTask
  File "/home/.pyenv/versions/3.8.7/envs/flyte_virtual_env/lib/python3.8/site-packages/flytekit/core/base_sql_task.py", line 4, in <module>
    from flytekit.core.base_task import PythonTask, TaskMetadata
  File "/home/.pyenv/versions/3.8.7/envs/flyte_virtual_env/lib/python3.8/site-packages/flytekit/core/base_task.py", line 26, in <module>
    from flytekit.common.tasks.sdk_runnable import ExecutionParameters
  File "/home/.pyenv/versions/3.8.7/envs/flyte_virtual_env/lib/python3.8/site-packages/flytekit/common/tasks/sdk_runnable.py", line 16, in <module>
    from flytekit.common import interface as _interface
  File "/home/.pyenv/versions/3.8.7/envs/flyte_virtual_env/lib/python3.8/site-packages/flytekit/common/interface.py", line 3, in <module>
    from flytekit.common import promise as _promise
  File "/home/.pyenv/versions/3.8.7/envs/flyte_virtual_env/lib/python3.8/site-packages/flytekit/common/promise.py", line 4, in <module>
    from flytekit.common.types import helpers as _type_helpers
  File "/home/.pyenv/versions/3.8.7/envs/flyte_virtual_env/lib/python3.8/site-packages/flytekit/common/types/helpers.py", line 8, in <module>
    from flytekit.models import literals as _literal_models
  File "/home/.pyenv/versions/3.8.7/envs/flyte_virtual_env/lib/python3.8/site-packages/flytekit/models/literals.py", line 9, in <module>
    from flytekit.models.core import types as _core_types
  File "/home/.pyenv/versions/3.8.7/envs/flyte_virtual_env/lib/python3.8/site-packages/flytekit/models/core/types.py", line 8, in <module>
    class EnumType(_common.FlyteIdlEntity):
  File "/home/.pyenv/versions/3.8.7/envs/flyte_virtual_env/lib/python3.8/site-packages/flytekit/models/core/types.py", line 20, in EnumType
    def to_flyte_idl(self) -> _types_pb2.EnumType:
AttributeError: module 'flyteidl.core.types_pb2' has no attribute 'EnumType'
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by EngHabu** [comment]
Thank you for reporting this @palchicz. We think pip ended up installing a yanked version of a dependent library (flyteidl).. do you mind running `pip show flyteidl` and report back what you see?

**Comment by palchicz** [comment]
No problem!

Name: flyteidl
Version: 1.0.0
Summary: IDL for Flyte Platform
Home-page: https://www.github.com/flyteorg/flyteidl
Author: None
Author-email: None
License: UNKNOWN
Location: /home/palchicz/.pyenv/versions/3.8.7/envs/flyte_bash_task/lib/python3.8/site-packages
Requires: protobuf
Required-by: flytekit

**Comment by eapolinario** [comment]
@palchicz , we're investigating an issue related to this version of flyteidl. The 1.0.0 version is marked as [yanked]( https://pypi.org/project/flyteidl/#history) in pypi but for some reason it's still being picked up.

So, in order to unblock you while we investigate this issue, can you run `pip install flyteidl==0.21.13`?

Also, what version of pip you're running in that venv?

**Comment by palchicz** [comment]
@eapolinario thanks for the flyteidl verion! Installing that version unblocked me. 

The version of pip running in that virtualenv is `20.2.3`
