### ISSUE TITLE
[BUG] Get execution details on GCP crashes admin

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#1954]
### Describe the bug

```
{"json":{"src":"base.go:54"},"level":"fatal","msg":"panic-ed for request: [id:\u003cnode_id:\"start-node\" execution_id:\u003cproject:\"flytesnacks\" domain:\"development\" name:\"f06dedc565f61443894e\" \u003e \u003e ] with err: runtime error: invalid memory address or nil pointer dereference with Stack: goroutine 1513 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/flyteorg/flyteadmin/pkg/rpc/adminservice.(*AdminService).interceptPanic(0xc0006e5000, {0x2431188, 0xc001372750}, {0x2412c38, 0xc001372780})\n\t/go/src/github.com/flyteorg/flyteadmin/pkg/rpc/adminservice/base.go:54 +0x85\npanic({0x1d474c0, 0x35b47c0})\n\t/usr/local/go/src/runtime/panic.go:1038 +0x215\ngithub.com/flyteorg/flyteadmin/pkg/manager/impl.(*NodeExecutionManager).GetNodeExecutionData(0xc000478fc0, {0x2431188, 0xc001372750}, {0xc000882300, {}, {0x0, 0x0, 0x0}, 0x0})\n\t/go/src/github.com/flyteorg/flyteadmin/pkg/manager/impl/node_execution_manager.go:474 +0x74f\ngithub.com/flyteorg/flyteadmin/pkg/rpc/adminservice.(*AdminService).GetNodeExecutionData.func1()\n\t/go/src/github.com/flyteorg/flyteadmin/pkg/rpc/adminservice/node_execution.go:135 +0x82\ngithub.com/flyteorg/flytestdlib/promutils.StopWatch.Time({{0x7f6ab42d1440, 0xc0017e2000}, 0x0}, 0xc0010f79e8)\n\t/go/pkg/mod/github.com/flyteorg/flytestdlib@v0.3.36/promutils/scope.go:64 +0xcb\ngithub.com/flyteorg/flyteadmin/pkg/rpc/adminservice/util.(*RequestMetrics).Time(...)\n\t/go/src/github.com/flyteorg/flyteadmin/pkg/rpc/adminservice/util/metrics.go:33\ngithub.com/flyteorg/flyteadmin/pkg/rpc/adminservice.(*AdminService).GetNodeExecutionData(0xc0006e5000, {0x2431188, 0xc001372750}, 0xc001372780)\n\t/go/src/github.com/flyteorg/flyteadmin/pkg/rpc/adminservice/node_execution.go:134 +0x1d2\ngithub.com/flyteorg/flyteidl/gen/pb-go/flyteidl/service._AdminService_GetNodeExecutionData_Handler.func1({0x2431188, 0xc001372750}, {0x1f127c0, 0xc001372780})\n\t/go/pkg/mod/github.com/flyteorg/flyteidl@v0.21.8/gen/pb-go/flyteidl/service/admin.pb.go:1484 +0x7b\ngithub.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1({0x2431188, 0xc001372750}, {0x1f127c0, 0xc001372780}, 0x18, 0xc000010d08)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0x87\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x2431188, 0xc001372750}, {0x1f127c0, 0xc001372780})\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:25 +0x3a\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x2431188, 0xc001372750}, {0x1f127c0, 0xc001372780}, 0xc001acbbb8, 0x1d45d80)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:34 +0xbf\ngithub.com/flyteorg/flyteidl/gen/pb-go/flyteidl/service._AdminService_GetNodeExecutionData_Handler({0x2006ac0, 0xc0006e5000}, {0x2431188, 0xc001372750}, 0xc0001016e0, 0xc00010e180)\n\t/go/pkg/mod/github.com/flyteorg/flyteidl@v0.21.8/gen/pb-go/flyteidl/service/admin.pb.go:1486 +0x138\ngoogle.golang.org/grpc.(*Server).processUnaryRPC(0xc0008b1180, {0x246a048, 0xc0005a3380}, 0xc0007ced00, 0xc001a5c420, 0x35cf8f8, 0x0)\n\t/go/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:1217 +0xc8f\ngoogle.golang.org/grpc.(*Server).handleStream(0xc0008b1180, {0x246a048, 0xc0005a3380}, 0xc0007ced00, 0x0)\n\t/go/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:1540 +0xa2a\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2()\n\t/go/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:878 +0x98\ncreated by google.golang.org/grpc.(*Server).serveStreams.func1\n\t/go/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:876 +0x294\n","ts":"2021-12-16T07:27:22Z"}
```

 Image:         cr.flyte.org/flyteorg/flyteadmin:v0.6.49

### Expected behavior

Flyteadmin shouldn't crash

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
@pmahindrakar-oss is this still an issue, folks are using flyteadmin on GCP, have not seen this?

**Comment by pmahindrakar-oss** [comment]
Yeah i have not seen this being reported and dont see this happening on our gcp deployment too. I am closing this for now and will reopen if we see this again
