### ISSUE TITLE
[Core feature]  No stacktraces

### ISSUE THREAD

**Issue by sonjaer** [flyteorg/flyte#1998]
### Motivation: Why do you think this is important?

I find it hard to debug/understand where these logged errors comes from without a stacktrace

```
json: {
exec_id: "cz7vntanluzg2fck4yim"
src: "protobuf_store.go:77"
}
level: "error"
msg: "Failed to write to the raw store [gs://flyte-production-storage/metadata/payment-risk-datasets/production/cz7vntanluzg2fck4yim/inputs] Error: Failed to write data [172b] to path [metadata/payment-risk-datasets/production/cz7vntanluzg2fck4yim/inputs].: googleapi: Error 409: The metadata for object "metadata/payment-risk-datasets/production/cz7vntanluzg2fck4yim/inputs" was edited during the operation. Please try again., conflict"
ts: "2021-12-27T05:33:19Z"
```

```
json: {
exec_id: "so5a7vr6wrndjvk7h3g7"
node: "ffum5wni"
src: "node_execution_manager.go:120"
}
level: "error"
msg: "failed to fetch node execution for the parent node: project:"daily-sessions" domain:"production" name:"so5a7vr6wrndjvk7h3g7"  fivcmqky with err%!(EXTRA *errors.flyteAdminErrorImpl=unexpected error type for: dial tcp 10.201.108.5:5432: connect: connection refused)"
ts: "2021-12-28T02:21:24Z"```
```

I am not very familiar with Go but it would be great to see a stacktrace being logged. 

### Goal: What should the final outcome look like, ideally?

Stacktrace when logging the error

### Describe alternatives you've considered 

None

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
@sonjaer if you look at the following log line, the `.json` portion of the log has `.json.src` This source tells you the filename and the line number of the original message
```
json: {
exec_id: "cz7vntanluzg2fck4yim"
src: "protobuf_store.go:77"
}
level: "error"
msg: "Failed to write to the raw store [gs://flyte-production-storage/metadata/payment-risk-datasets/production/cz7vntanluzg2fck4yim/inputs] Error: Failed to write data [172b] to path [metadata/payment-risk-datasets/production/cz7vntanluzg2fck4yim/inputs].: googleapi: Error 409: The metadata for object "metadata/payment-risk-datasets/production/cz7vntanluzg2fck4yim/inputs" was edited during the operation. Please try again., conflict"
ts: "2021-12-27T05:33:19Z"
``

**Comment by sonjaer** [comment]
> @sonjaer if you look at the following log line, the `.json` portion of the log has `.json.src` This source tells you the filename and the line number of the original message
> 
> ```
> json: {
> exec_id: "cz7vntanluzg2fck4yim"
> src: "protobuf_store.go:77"
> }
> level: "error"
> msg: "Failed to write to the raw store [gs://flyte-production-storage/metadata/payment-risk-datasets/production/cz7vntanluzg2fck4yim/inputs] Error: Failed to write data [172b] to path [metadata/payment-risk-datasets/production/cz7vntanluzg2fck4yim/inputs].: googleapi: Error 409: The metadata for object "metadata/payment-risk-datasets/production/cz7vntanluzg2fck4yim/inputs" was edited during the operation. Please try again., conflict"
> ts: "2021-12-27T05:33:19Z"
> ``
> ```

Yes I saw that, that's good. I was looking to know from which method that method was called, like

```
"Failed to start execution for flyte-canary#flyte-canary.production.bigquery-canary#2021-12-29T09:20:00Z
	com.spotify.styx.flyte.FlyteRunner$CreateExecutionException: Couldn't create execution for:FlyteExecConf{referenceId=LAUNCH_PLAN:flyte-canary:production:bigquery_canary:5072050406517021b5969d65748e0a18cbcf065d, inputFields={}}
	at com.spotify.styx.flyte.FlyteAdminClientRunner.createExecution(FlyteAdminClientRunner.java:208)
	at com.spotify.styx.flyte.RoutingFlyteRunner.createExecution(RoutingFlyteRunner.java:41)
	at com.spotify.styx.state.handlers.FlyteRunnerHandler.transitionSubmitting(FlyteRunnerHandler.java:87)
	at com.spotify.styx.state.handlers.FlyteRunnerHandler.safeTransitionInto(FlyteRunnerHandler.java:62)
	at com.spotify.styx.state.handlers.AbstractRunnerHandler.transitionInto(AbstractRunnerHandler.java:71)
	at jdk.internal.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
	at  
``
```
