### ISSUE TITLE
[BUG] Github util tests fails intermittently due to RateLimitError

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#2173]
### Describe the bug

Ideally we dont want unit tests to perform API queries and instead use mocked data

```
--- FAIL: TestGetLatestVersion (1.45s)
    --- FAIL: TestGetLatestVersion/Get_latest_release (0.06s)
        githubutil_test.go:23: 
            	Error Trace:	githubutil_test.go:23
            	Error:      	Expected nil, but got: &github.RateLimitError{Rate:github.Rate{Limit:60, Remaining:0, Reset:time.Date(2022, time.February, 16, 19, 39, 57, 0, time.Local)}, Response:(*http.Response)(0xc0000bd3b0), Message:"API rate limit exceeded for 49.36.109.254. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"}
            	Test:       	TestGetLatestVersion/Get_latest_release
--- FAIL: TestGetLatestRelease (0.02s)
    githubutil_test.go:29: 
        	Error Trace:	githubutil_test.go:29
        	Error:      	Expected nil, but got: &github.RateLimitError{Rate:github.Rate{Limit:60, Remaining:0, Reset:time.Date(2022, time.February, 16, 19, 39, 57, 0, time.Local)}, Response:(*http.Response)(0xc0000bd440), Message:"API rate limit exceeded for 49.36.109.254. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"}
        	Test:       	TestGetLatestRelease
    githubutil_test.go:30: 
        	Error Trace:	githubutil_test.go:30
        	Error:      	Not equal: 
        	            	expected: true
        	            	actual  : false
        	Test:       	TestGetLatestRelease
--- FAIL: TestCheckVersionExist (0.04s)
    --- FAIL: TestCheckVersionExist/Valid_Tag (0.02s)
        githubutil_test.go:40: 
            	Error Trace:	githubutil_test.go:40
            	Error:      	Expected nil, but got: &github.RateLimitError{Rate:github.Rate{Limit:60, Remaining:0, Reset:time.Date(2022, time.February, 16, 19, 39, 57, 0, time.Local)}, Response:(*http.Response)(0xc0001e8750), Message:"API rate limit exceeded for 49.36.109.254. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"}
            	Test:       	TestCheckVersionExist/Valid_Tag
        githubutil_test.go:41: 
            	Error Trace:	githubutil_test.go:41
            	Error:      	Not equal: 
            	            	expected: true
            	            	actual  : false
            	Test:       	TestCheckVersionExist/Valid_Tag
--- FAIL: TestGetSHAFromVersion (0.03s)
    --- FAIL: TestGetSHAFromVersion/Valid_Tag (0.01s)
        githubutil_test.go:52: 
            	Error Trace:	githubutil_test.go:52
            	Error:      	Expected nil, but got: &github.RateLimitError{Rate:github.Rate{Limit:60, Remaining:0, Reset:time.Date(2022, time.February, 16, 19, 39, 57, 0, time.Local)}, Response:(*http.Response)(0xc0005e8000), Message:"API rate limit exceeded for 49.36.109.254. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"}
            	Test:       	TestGetSHAFromVersion/Valid_Tag
        assertion_compare.go:313: 
            	Error Trace:	githubutil_test.go:53
            	Error:      	"0" is not greater than "0"
            	Test:       	TestGetSHAFromVersion/Valid_Tag
            	Messages:   	[]
--- FAIL: TestGetAssetsFromRelease (0.01s)
    --- FAIL: TestGetAssetsFromRelease/Successful_get_assets (0.01s)
        githubutil_test.go:60: 
            	Error Trace:	githubutil_test.go:60
            	Error:      	Expected nil, but got: &github.RateLimitError{Rate:github.Rate{Limit:60, Remaining:0, Reset:time.Date(2022, time.February, 16, 19, 39, 58, 0, time.Local)}, Response:(*http.Response)(0xc0005e8090), Message:"API rate limit exceeded for 49.36.109.254. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"}
            	Test:       	TestGetAssetsFromRelease/Successful_get_assets
        githubutil_test.go:61: 
            	Error Trace:	githubutil_test.go:61
            	Error:      	Expected value not to be nil.
            	Test:       	TestGetAssetsFromRelease/Successful_get_assets
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1714fea]

goroutine 57 [running]:
testing.tRunner.func1.2({0x177e5e0, 0x1ca79a0})
	/usr/local/Cellar/go/1.17.5/libexec/src/testing/testing.go:1209 +0x36c
testing.tRunner.func1()
	/usr/local/Cellar/go/1.17.5/libexec/src/testing/testing.go:1212 +0x3b6
panic({0x177e5e0, 0x1ca79a0})
	/usr/local/Cellar/go/1.17.5/libexec/src/runtime/panic.go:1047 +0x266
github.com/flyteorg/flytectl/pkg/util/githubutil.TestGetAssetsFromRelease.func1(0x0)
	/Users/praful/flytectl/pkg/util/githubutil/githubutil_test.go:62 +0xca
testing.tRunner(0xc000102d00, 0x1835720)
	/usr/local/Cellar/go/1.17.5/libexec/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
```

### Expected behavior

Consistent behavior for tests

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by evalsocket** [comment]
@pmahindrakar-oss Please add `GITHUB_TOKEN` in your env variable, It will fix the issue

**Comment by pmahindrakar-oss** [comment]
Thanks @evalsocket . How does the community get this token and is there a README for it . If not then we can add a note for it. Ideally would prefer if it doesn't call the API while running unit tests. Without an internet connection if i am able to checkin and test code that would be hugely be helpful.
