### ISSUE TITLE
[Core feature] Support imperative workflows in pyflyte run

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#2383]
### Motivation: Why do you think this is important?

Imperative workflows are a way of programmatically creating workflows. Currently, these types of workflows are not supported by `pyflyte run`:

```
Traceback (most recent call last):
  File "/Users/nielsbantilan/miniconda3/envs/flytesnacks/bin/pyflyte", line 8, in <module>
    sys.exit(main())
  File "/Users/nielsbantilan/miniconda3/envs/flytesnacks/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nielsbantilan/miniconda3/envs/flytesnacks/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/nielsbantilan/miniconda3/envs/flytesnacks/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/nielsbantilan/miniconda3/envs/flytesnacks/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nielsbantilan/miniconda3/envs/flytesnacks/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/nielsbantilan/miniconda3/envs/flytesnacks/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/nielsbantilan/miniconda3/envs/flytesnacks/lib/python3.8/site-packages/flytekit/clis/sdk_in_container/run.py", line 152, in run
    wf = remote.register_script(
  File "/Users/nielsbantilan/miniconda3/envs/flytesnacks/lib/python3.8/site-packages/flytekit/remote/remote.py", line 512, in register_script
    _, _, _, fname = tracker.extract_task_module(entity)
  File "/Users/nielsbantilan/miniconda3/envs/flytesnacks/lib/python3.8/site-packages/flytekit/core/tracker.py", line 237, in extract_task_module
    name = f.__name__.split(".")[-1]
AttributeError: 'ImperativeWorkflow' object has no attribute '__name__'
```

This is important because users who use this style of workflow definition won't be able to use pyflyte run

### Goal: What should the final outcome look like, ideally?

One should be able to define an imperative workflow and run it with `pyflyte run`

### Describe alternatives you've considered 

NA

###  Propose: Link/Inline OR Additional context 

This flytesnacks example won't work: https://docs.flyte.org/projects/cookbook/en/latest/auto/core/flyte_basics/imperative_wf_style.html#sphx-glr-auto-core-flyte-basics-imperative-wf-style-py

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pingsutw** [comment]
Upgrading flytekit to `v0.32.6` can fix it.

**Comment by kumare3** [comment]
@pingsutw is this resolved now?

**Comment by pingsutw** [comment]
yeah, we have fixed it.
