### ISSUE TITLE
[BUG] Registering the same workflow twice causes an invalid argument error

### ISSUE THREAD

**Issue by vvasavada-fn** [flyteorg/flyte#2508]
### Describe the bug

I have a workflow that directly calls two workflows. The first time I register it, it completes successfully. In subsequent times, we would expect it to skip the workflow / tasks, because there are no changes and the registration already happened. However, sometimes when you go to register again, instead of skipping, it produces an error like this:

```
{"asctime": "2022-05-17 18:26:58,080", "name": "flytekit.cli", "levelname": "ERROR", "message": "Error creating Flyte entity because of invalid arguments. Create request: "}
{<dumps the entire pb of the workflow>}
Traceback (most recent call last):
  File "/fn/bin/flyte-cli", line 8, in <module>
    sys.exit(_flyte_cli())
  File "/fn/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/fn/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/fn/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/fn/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/fn/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/fn/lib/python3.9/site-packages/flytekit/clis/flyte_cli/main.py", line 1775, in register_files
    _extract_and_register(client, project, domain, version, files, patches)
  File "/fn/lib/python3.9/site-packages/flytekit/clis/flyte_cli/main.py", line 1711, in _extract_and_register
    client.raw.create_workflow(_workflow_pb2.WorkflowCreateRequest(id=id, spec=flyte_entity))
  File "/fn/lib/python3.9/site-packages/flytekit/clients/raw.py", line 128, in handler
    return fn(*args, **kwargs)
  File "/fn/lib/python3.9/site-packages/flytekit/clients/raw.py", line 170, in handler
    raise e
  File "/fn/lib/python3.9/site-packages/flytekit/clients/raw.py", line 163, in handler
    fn(self, create_request)
  File "/fn/lib/python3.9/site-packages/flytekit/clients/raw.py", line 350, in create_workflow
    return self._stub.CreateWorkflow(workflow_create_request, metadata=self._metadata)
  File "/fn/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/fn/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "workflow with different structure already exists with id resource_type:WORKFLOW project:"flyte-sandbox-jeevb" domain:"main" name:"sandbox.subworkflow.parent_workflow" version:"vrinda-spike-a3c802abfbd5" "
	debug_error_string = "{"created":"@1652812018.080534684","description":"Error received from peer ipv4:192.168.65.2:64766","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"workflow with different structure already exists with id resource_type:WORKFLOW project:"flyte-sandbox-jeevb" domain:"main" name:"sandbox.subworkflow.parent_workflow" version:"vrinda-spike-a3c802abfbd5" ","grpc_status":3}"
```

Here is an example dummy workflow of this format that should be reproducible:

```
from flytekit import task, workflow


@task
def hello(username: str) -> str:
    return f"Hello, {username}!"


@workflow
def child_workflow(username: str) -> str:
    hello_output = hello(username=username)
    return hello_output


@task
def hello_again(username: str) -> str:
    return f"Hello, {username}!"


@workflow
def second_child_workflow(hello_output: str) -> str:
    return hello_again(username=hello_output)


@workflow
def parent_workflow(input_value: str) -> str:
    child_workflow_output = child_workflow(username=input_value)
    second_child_workflow_output = second_child_workflow(
        hello_output=child_workflow_output
    )
    return second_child_workflow_output
```

We looked into the serialized files that are created before registration, and the only differences between calls are the order of the subworkflows (i.e. the original one has `sandbox.subworkflow.second_child_workflow` listed first, and the subsequent registration has `sandbox.subworkflow.child_workflow` listed first).

Changing [this line](https://github.com/flyteorg/flytekit/blob/5907e766a01058181697de2babd779588e5d48b0/flytekit/tools/translator.py#L292) to `sub_workflows=sorted(set(sub_wfs), key=lambda x: x.short_string())` fixes the error, but not sure if that is where the problem stems from.

This is observed on `flytekit` version `0.30.3` and flyeidl version `0.22.3`.

### Expected behavior

Already registered workflows should be skipped with no errors.

### Screenshots

Happy to share the serialized files if that is helpful! 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
ohh no, can you propose a fix?

**Comment by vvasavada-fn** [comment]
I think changing [this](https://github.com/flyteorg/flytekit/blob/5907e766a01058181697de2babd779588e5d48b0/flytekit/tools/translator.py#L292) to `sub_workflows=sorted(set(sub_wfs), key=lambda x: x.short_string())` should fix it? thoughts?

**Comment by wild-endeavor** [comment]
sounds good.  Let's do it.
