### ISSUE TITLE
[Housekeeping] [flytekit] Improve handling in pyflyte register/package

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#2638]
# Housekeeping items
## Error messages
Both pyflyte register and package do not have very good error messages when you just run them. 

```
 $ pyflyte register
Traceback (most recent call last):
  File "/Users/ytong/envs/flytekit/bin/pyflyte", line 33, in <module>
    sys.exit(load_entry_point('flytekit', 'console_scripts', 'pyflyte')())
  File "/Users/ytong/envs/flytekit/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ytong/envs/flytekit/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/ytong/envs/flytekit/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ytong/envs/flytekit/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ytong/envs/flytekit/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ytong/envs/flytekit/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/ytong/go/src/github.com/flyteorg/flytekit/flytekit/clis/sdk_in_container/register.py", line 139, in register
    zip_file = fast_package(detected_root, output)
  File "/Users/ytong/go/src/github.com/flyteorg/flytekit/flytekit/tools/fast_registration.py", line 30, in fast_package
    ignore = IgnoreGroup(source, [GitIgnore, DockerIgnore, StandardIgnore])
  File "/Users/ytong/go/src/github.com/flyteorg/flytekit/flytekit/tools/ignore.py", line 110, in __init__
    self.ignores = [ignore(root) for ignore in ignores]
  File "/Users/ytong/go/src/github.com/flyteorg/flytekit/flytekit/tools/ignore.py", line 110, in <listcomp>
    self.ignores = [ignore(root) for ignore in ignores]
  File "/Users/ytong/go/src/github.com/flyteorg/flytekit/flytekit/tools/ignore.py", line 74, in __init__
    self.pm = self._parse()
  File "/Users/ytong/go/src/github.com/flyteorg/flytekit/flytekit/tools/ignore.py", line 78, in _parse
    dockerignore = os.path.join(self.root, ".dockerignore")
  File "/usr/local/Cellar/python@3.8/3.8.13_1/bin/../Frameworks/Python.framework/Versions/3.8/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
$ pyflyte package
No packages to scan for flyte entities. Aborting!
```
We should make it so that the help message shows up along with a nice error when there is an error.  See `pyflyte run` which handles it better.

## Temp files
Both pyflyte `package --fast` and `register` (and I think `run` too) will produce a .tgz file in the local directory.  This is part of the "fast registration" process (read more about that [here](https://docs.flyte.org/projects/cookbook/en/latest/auto/deployment/deploying_workflows.html#fast-registration)).  If the user doesn't delete this though, then the next time, the tgz file itself gets bundled with the second .tgz file, thus doubling the size of the file every time.  This is just a bit annoying - we should be creating a temporary (but persistent) folder for these somewhere else on the FS.  That way, if the user wants to look at it after the fact, they can, but if they don't, they don't need to be bothered with the cleanup and the OS will just remove them eventually.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wild-endeavor** [comment]
@[madhur-tandon](https://github.com/madhur-tandon)
