### ISSUE TITLE
[BUG] Flytectl crashes on registration of workflow definitions coming from flytekit-java

### ISSUE THREAD

**Issue by sbrunk** [flyteorg/flyte#2723]
### Describe the bug

Flytectl 0.6.5, when trying to register serialized task/workflow definitions serialized with flytekit-java/jflyte, crashes with a segfault:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1edd4ec]

goroutine 1 [running]:
github.com/flyteorg/flytectl/cmd/register.hydrateIdentifier(0x0, {0x7ff7bfeff64c, 0x2}, 0x0)
        /home/runner/work/flytectl/flytectl/cmd/register/register_util.go:255 +0x2c
github.com/flyteorg/flytectl/cmd/register.hydrateSpec({0x2f304c8?, 0xc000a6d7a0?}, {0x0, 0x0}, {{0x7ff7bfeff64c, 0x2}, 0x0, 0x0, 0x0, {0x0, ...}, ...})
        /home/runner/work/flytectl/flytectl/cmd/register/register_util.go:462 +0xdd
github.com/flyteorg/flytectl/cmd/register.registerFile({0x2f3dc28, 0xc000120000}, {0x7ff7bfeff5e7, _}, {_, _, _}, {0x0, {0x0, 0x0}, ...}, ...)
        /home/runner/work/flytectl/flytectl/cmd/register/register_util.go:594 +0x488
github.com/flyteorg/flytectl/cmd/register.Register({0x2f3dc28, 0xc000120000}, {0xc0003b3810?, 0x0?, 0x0?}, 0x3f20520, {0x0, {0x0, 0x0}, {0x0, ...}, ...})
        /home/runner/work/flytectl/flytectl/cmd/register/files.go:160 +0x6ca
github.com/flyteorg/flytectl/cmd/register.registerFromFilesFunc({0x2f3dc28, 0xc000120000}, {0xc0003b3810, 0x1, 0x7}, {0x0, {0x0, 0x0}, {0x0, 0x0}, ...})
        /home/runner/work/flytectl/flytectl/cmd/register/files.go:118 +0xcd
github.com/flyteorg/flytectl/cmd/core.generateCommandFunc.func1(0xc000319180?, {0xc0003b3810, 0x1, 0x7})
        /home/runner/work/flytectl/flytectl/cmd/core/cmd.go:65 +0x625
github.com/spf13/cobra.(*Command).execute(0xc000319180, {0xc0003b37a0, 0x7, 0x7})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00051db80)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x39c
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/flyteorg/flytectl/cmd.ExecuteCmd()
        /home/runner/work/flytectl/flytectl/cmd/root.go:137 +0x1e
main.main()
        /home/runner/work/flytectl/flytectl/main.go:12 +0x1d
```

### Expected behavior

flytectl should not crash. It should succeed or produce a useful error message if the input is invalid.

### Additional context to reproduce

```bash
git clone https://github.com/spotify/flytekit-java.git
cd flytekit-java
git checkout 0.3.15 # we need to use the previous release as there is another issue currently with 0.3.16
mvn package -DskipTests=true

flytectl sandbox start # we need a sandbox because jflyte wants to upload jars even on serialize currently
cat <<EOF > .env.local
FLYTE_PLATFORM_URL=localhost:30081
FLYTE_AWS_ENDPOINT=http://localhost:30084
FLYTE_AWS_ACCESS_KEY_ID=minio
FLYTE_AWS_SECRET_ACCESS_KEY=miniostorage
FLYTE_STAGING_LOCATION=s3://my-s3-bucket
FLYTE_PLATFORM_INSECURE=True
EOF


mkdir  _pb_output
scripts/jflyte serialize workflows -cp=flytekit-examples-scala/target/lib -f  _pb_output

flytectl register files  _pb_output/* -d development  -p flytesnacks  --version v1 # segfault
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by evalsocket** [comment]
cc: @pmahindrakar-oss

**Comment by pmahindrakar-oss** [comment]
@sbrunk seems the serialized files  from flytekit-java might not be generating the identifier for the taskSpec
```
hydrateIdentifier(taskSpec.Template.Id, config.Version, config.Force)
```
And hence throwing this nil pointer.

I agree we should handle this gracefully in flytectl though validation on the serialized files

**Comment by eapolinario** [comment]
@sbrunk , is this still applicable? Can we make sure we have a test in flytekit-java tht handles this case?
