### ISSUE TITLE
[BUG] flytectl sandbox /demo crash while switching kubecontext

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#2767]
### Describe the bug

Slack thread https://flyte-org.slack.com/archives/CREL4QVAQ/p1659058509465339

```
INFO[0000] [0] Couldn't find a config file []. Relying on env vars and pflags. 
🧑‍🏭 Bootstrapping a brand new flyte cluster... 🔨 🔧
delete existing sandbox cluster [y/n]: y
cr.flyte.org/flyteorg/flyte-sandbox-lite:sha-2635cda85b24926632f0d7391975732ab221fe1b Fully Qualified image
🐋 Running Flyte v1.1.0 release
🐋 pulling docker image for release cr.flyte.org/flyteorg/flyte-sandbox-lite:sha-2635cda85b24926632f0d7391975732ab221fe1b
{"status":"Pulling from flyteorg/flyte-sandbox-lite","id":"sha-2635cda85b24926632f0d7391975732ab221fe1b"}
{"status":"Digest: sha256:b60955127757a9dd34f5ec3dea59982491a06fbb5430741da90dfe286505eb65"}
{"status":"Status: Image is up to date for cr.flyte.org/flyteorg/flyte-sandbox-lite:sha-2635cda85b24926632f0d7391975732ab221fe1b"}
🧑‍🏭 booting Flyte-sandbox container
92022-07-28T13:47:59.014826126Z Starting Docker daemon...
%2022-07-28T13:48:00.129797460Z Done.
72022-07-28T13:48:00.129842043Z Starting k3s cluster...
%2022-07-28T13:48:03.566679961Z Done.
unexpected fault address 0x360808085a175a75
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x360808085a175a75 pc=0x1024fc560]

goroutine 1 [running]:
runtime.throw({0x10392f141?, 0x30?})
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/panic.go:992 +0x50 fp=0x1400066dc20 sp=0x1400066dbf0 pc=0x1024cf590
runtime.sigpanic()
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/signal_unix.go:825 +0x1a4 fp=0x1400066dc50 sp=0x1400066dc20 pc=0x1024e5704
aeshashbody()
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/asm_arm64.s:878 +0x2d0 fp=0x1400066dc60 sp=0x1400066dc60 pc=0x1024fc560
runtime.mapiternext(0x140003af440)
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/map.go:934 +0x2c4 fp=0x1400066dcd0 sp=0x1400066dc60 pc=0x1024aad94
runtime.mapiterinit(0x1400066dd28?, 0x7?, 0x100000002?)
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/map.go:861 +0x2f0 fp=0x1400066dd00 sp=0x1400066dcd0 pc=0x1024aaa90
reflect.mapiterinit(0x1400007c900?, 0x0?, 0x0?)
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/map.go:1373 +0x20 fp=0x1400066dd30 sp=0x1400066dd00 pc=0x1024f8ca0
github.com/modern-go/reflect2.(*UnsafeMapType).UnsafeIterate(...)
	/home/runner/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/unsafe_map.go:112
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0x14000c2f4a0, 0x14000c0c748, 0x1400012b6e0)
	/home/runner/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_map.go:291 +0x244 fp=0x1400066deb0 sp=0x1400066dd30 pc=0x103025384
github.com/json-iterator/go.(*placeholderEncoder).Encode(0x1400066df01?, 0x1400012b6f8?, 0x1400066df58?)
	/home/runner/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:332 +0x2c fp=0x1400066dee0 sp=0x1400066deb0 pc=0x10301e42c
github.com/json-iterator/go.(*structFieldEncoder).Encode(0x14000c2f710, 0x103d22459?, 0x1400012b6e0)
	/home/runner/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_encoder.go:110 +0x58 fp=0x1400066df60 sp=0x1400066dee0 pc=0x1030319f8
github.com/json-iterator/go.(*structEncoder).Encode(0x14000c2f770, 0x5e5?, 0x1400012b6e0)
	/home/runner/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_encoder.go:158 +0x708 fp=0x1400066e050 sp=0x1400066df60 pc=0x103032378
github.com/json-iterator/go.(*OptionalEncoder).Encode(0x1400012b6e0?, 0x14000939d70?, 0x1400066e0f8?)
	/home/runner/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_optional.go:70 +0xcc fp=0x1400066e0b0 sp=0x1400066e050 pc=0x10302a69c
github.com/json-iterator/go.(*placeholderEncoder).Encode(0x1400066e101?, 0x1400012b6f8?, 0x1400066e158?)
	/home/runner/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:332 +0x2c fp=0x1400066e0e0 sp=0x1400066e0b0 pc=0x10301e42c
github.com/json-iterator/go.(*structFieldEncoder).Encode(0x14000c36ea0, 0x103d8c098?, 0x1400012b6e0)
	/home/runner/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_encoder.go:110 +0x58 fp=0x1400066e160 sp=0x1400066e0e0 pc=0x1030319f8
github.com/json-iterator/go.(*structEncoder).Encode(0x14000c36f60, 0x14000bf6ff0?, 0x1400012b6e0)
	/home/runner/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_encoder.go:158 +0x708 fp=0x1400066e250 sp=0x1400066e160 pc=0x103032378
github.com/json-iterator/go.(*placeholderEncoder).Encode(0x140001f7e01?, 0x1400012b6f8?, 0x1400066e2f8?)
	/home/runner/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:332 +0x2c fp=0x1400066e280 sp=0x1400066e250 pc=0x10301e42c
github.com/json-iterator/go.(*structFieldEncoder).Encode(0x14000c371d0, 0x103d22369?, 0x1400012b6e0)
	/home/runner/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_encoder.go:110 +0x58 fp=0x1400066e300 sp=0x1400066e280 pc=0x1030319f8
github.com/json-iterator/go.(*structEncoder).Encode(0x14000c37230, 0x1024a525c?, 0x1400012b6e0)
	/home/runner/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_encoder.go:158 +0x708 fp=0x1400066e3f0 sp=0x1400066e300 pc=0x103032378
github.com/json-iterator/go.(*sliceEncoder).Encode(0x14000c0cc00, 0x1400032a738, 0x1400012b6e0)
	/home/runner/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_slice.go:38 +0x2f4 fp=0x1400066e4b0 sp=0x1400066e3f0 pc=0x10302b104
github.com/json-iterator/go.(*structFieldEncoder).Encode(0x14000c37d40, 0x103d2c79d?, 0x1400012b6e0)
	/home/runner/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_encoder.go:110 +0x58 fp=0x1400066e530 sp=0x1400066e4b0 pc=0x1030319f8
github.com/json-iterator/go.(*structEncoder).Encode(0x14000c37e30, 0x1400000f368?, 0x1400012b6e0)
	/home/runner/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_encoder.go:158 +0x708 fp=0x1400066e620 sp=0x1400066e530 pc=0x103032378
github.com/json-iterator/go.(*OptionalEncoder).Encode(0x10404fb40?, 0x14000864e60?, 0x0?)
	/home/runner/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_optional.go:70 +0xcc fp=0x1400066e680 sp=0x1400066e620 pc=0x10302a69c
github.com/json-iterator/go.(*onePtrEncoder).Encode(0x14000c3e2b0, 0x1400032a6e0, 0x14000b865a0?)
	/home/runner/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:219 +0x8c fp=0x1400066e6c0 sp=0x1400066e680 pc=0x10301da3c
github.com/json-iterator/go.(*Stream).WriteVal(0x1400012b6e0, {0x10404fb40, 0x1400032a6e0})
	/home/runner/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:98 +0x174 fp=0x1400066e740 sp=0x1400066e6c0 pc=0x10301ce04
github.com/json-iterator/go.(*frozenConfig).Marshal(0x14000864e60, {0x10404fb40, 0x1400032a6e0})
	/home/runner/go/pkg/mod/github.com/json-iterator/go@v1.1.10/config.go:299 +0x88 fp=0x1400066e7e0 sp=0x1400066e740 pc=0x103014348
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).doEncode(0x103cf4088?, {0x10427b590?, 0x1400032a6e0?}, {0x10426dcc8, 0x14000c0b890})
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/runtime/serializer/json/json.go:306 +0x54 fp=0x1400066e880 sp=0x1400066e7e0 pc=0x103393ac4
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0x1400005e5a0, {0x10427b590, 0x1400032a6e0}, {0x10426dcc8, 0x14000c0b890})
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/runtime/serializer/json/json.go:301 +0xe4 fp=0x1400066e8e0 sp=0x1400066e880 pc=0x103393a24
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).doEncode(0x14000424000, {0x10427b540?, 0x1400012b620}, {0x10426dcc8, 0x14000c0b890})
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/runtime/serializer/versioning/versioning.go:244 +0x670 fp=0x1400066ec40 sp=0x1400066e8e0 pc=0x103397fd0
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0x14000424000, {0x10427b540, 0x1400012b620}, {0x10426dcc8, 0x14000c0b890})
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/runtime/serializer/versioning/versioning.go:184 +0xe4 fp=0x1400066eca0 sp=0x1400066ec40 pc=0x103397914
k8s.io/apimachinery/pkg/runtime.Encode({0x12cb36e58, 0x14000424000}, {0x10427b540, 0x1400012b620})
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/runtime/codec.go:50 +0x64 fp=0x1400066ece0 sp=0x1400066eca0 pc=0x103042924
k8s.io/client-go/tools/clientcmd.Write(...)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.21.3/tools/clientcmd/loader.go:466
k8s.io/client-go/tools/clientcmd.WriteToFile({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x14000c0b020}, 0x14000c0b050, 0x14000c0b080, 0x14000c0b0b0, {0x1039413b8, ...}, ...}, ...)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.21.3/tools/clientcmd/loader.go:419 +0xe4 fp=0x1400066ed60 sp=0x1400066ece0 pc=0x10391d0b4
k8s.io/client-go/tools/clientcmd.writeCurrentContext({0x10428d718, 0x14000280640}, {0x1039413b8, 0xd})
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.21.3/tools/clientcmd/config.go:415 +0x148 fp=0x1400066ef50 sp=0x1400066ed60 pc=0x10391a648
k8s.io/client-go/tools/clientcmd.ModifyConfig({0x10428d718, 0x14000280640}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x14000be3860}, 0x14000be3890, 0x14000be38c0, ...}, ...)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.21.3/tools/clientcmd/config.go:197 +0x168 fp=0x1400066f680 sp=0x1400066ef50 pc=0x103919458
github.com/flyteorg/flytectl/pkg/k8s.(*ContextManager).CopyContext(0x14000b9b960, {0x10428d718, 0x140002805a0}, {0x10393305f, 0x7}, {0x1039413b8, 0xd})
	/home/runner/work/flytectl/flytectl/pkg/k8s/k8s.go:94 +0x474 fp=0x1400066f7e0 sp=0x1400066f680 pc=0x103921714
github.com/flyteorg/flytectl/pkg/sandbox.UpdateLocalKubeContext({0x10393305f, 0x7}, {0x1039413b8, 0xd})
/home/runner/work/flytectl/flytectl/pkg/sandbox/start.go:149 +0x180 fp=0x1400066f840 sp=0x1400066f7e0 pc=0x1039225e0
github.com/flyteorg/flytectl/pkg/sandbox.StartCluster({0x10428bd08, 0x1400019a000}, {0x1400099f9d8?, 0x102e39880?, 0x1400099f9a8?}, 0x10269a48c?, 0x1, {0x10398651f, 0x28}, {0x10392c572, ...}, ...)
	/home/runner/work/flytectl/flytectl/pkg/sandbox/start.go:265 +0x180 fp=0x1400066f960 sp=0x1400066f840 pc=0x1039231e0
github.com/flyteorg/flytectl/pkg/sandbox.StartDemoCluster({0x10428bd08, 0x1400019a000}, {0x105273270, 0x0, 0x0}, 0x0?)
	/home/runner/work/flytectl/flytectl/pkg/sandbox/start.go:287 +0x80 fp=0x1400066f9f0 sp=0x1400066f960 pc=0x1039234c0
github.com/flyteorg/flytectl/cmd/demo.startDemoCluster({0x10428bd08?, 0x1400019a000?}, {0x105273270?, 0x0?, 0x103957e29?}, {0x0, {0x0, 0x0}, {0x0, 0x0}, ...})
	/home/runner/work/flytectl/flytectl/cmd/demo/start.go:79 +0x64 fp=0x1400066fa30 sp=0x1400066f9f0 pc=0x103923fa4
github.com/flyteorg/flytectl/cmd/core.generateCommandFunc.func1(0x14000655680?, {0x105273270, 0x0, 0x0})
	/home/runner/work/flytectl/flytectl/cmd/core/cmd.go:65 +0x508 fp=0x1400066fd60 sp=0x1400066fa30 pc=0x102e41968
github.com/spf13/cobra.(*Command).execute(0x14000655680, {0x105273270, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x4c4 fp=0x1400066fe40 sp=0x1400066fd60 pc=0x102631514
github.com/spf13/cobra.(*Command).ExecuteC(0x14000193180)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x34c fp=0x1400066ff00 sp=0x1400066fe40 pc=0x102631a6c
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/flyteorg/flytectl/cmd.ExecuteCmd()
	/home/runner/work/flytectl/flytectl/cmd/root.go:137 +0x24 fp=0x1400066ff20 sp=0x1400066ff00 pc=0x10392aaf4
main.main()
	/home/runner/work/flytectl/flytectl/main.go:12 +0x20 fp=0x1400066ff70 sp=0x1400066ff20 pc=0x10392ac20
runtime.main()
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/proc.go:250 +0x250 fp=0x1400066ffd0 sp=0x1400066ff70 pc=0x1024d1ad0
runtime.goexit()
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/asm_arm64.s:1263 +0x4 fp=0x1400066ffd0 sp=0x1400066ffd0 pc=0x1024ff4c4

goroutine 19 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x0?)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1164 +0x60
created by k8s.io/klog/v2.init.0
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:418 +0x154

goroutine 9 [select]:
go.opencensus.io/stats/view.(*worker).start(0x14000394300)
	/home/runner/go/pkg/mod/go.opencensus.io@v0.22.6/stats/view/worker.go:276 +0x88
created by go.opencensus.io/stats/view.init.0
	/home/runner/go/pkg/mod/go.opencensus.io@v0.22.6/stats/view/worker.go:34 +0xa8

goroutine 14 [select]:
net/http.(*persistConn).readLoop(0x1400087d8c0)
	/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/transport.go:2213 +0xc2c
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/transport.go:1750 +0x11f4

goroutine 15 [select]:
net/http.(*persistConn).writeLoop(0x1400087d8c0)
	/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/transport.go:2392 +0xa4
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/transport.go:1751 +0x1240

goroutine 88 [IO wait]:
internal/poll.runtime_pollWait(0x12cccc128, 0x72)
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/netpoll.go:302 +0xa4
internal/poll.(*pollDesc).wait(0x14000394d80?, 0x14000802000?, 0x0)
	/opt/hostedtoolcache/go/1.18.3/x64/src/internal/poll/fd_poll_runtime.go:83 +0x2c
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.18.3/x64/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0x14000394d80, {0x14000802000, 0x20b1, 0x20b1})
	/opt/hostedtoolcache/go/1.18.3/x64/src/internal/poll/fd_unix.go:167 +0x1e4
net.(*netFD).Read(0x14000394d80, {0x14000802000?, 0x14000a74768?, 0x1024b01f8?})
	/opt/hostedtoolcache/go/1.18.3/x64/src/net/fd_posix.go:55 +0x2c
net.(*conn).Read(0x1400000e800, {0x14000802000?, 0x14000a747a8?, 0x1024b225c?})
	/opt/hostedtoolcache/go/1.18.3/x64/src/net/net.go:183 +0x38
crypto/tls.(*atLeastReader).Read(0x140008b9bc0, {0x14000802000?, 0x0?, 0x1024a6038?})
	/opt/hostedtoolcache/go/1.18.3/x64/src/crypto/tls/conn.go:785 +0x44
bytes.(*Buffer).ReadFrom(0x140007ab3f8, {0x10426de88, 0x140008b9bc0})
	/opt/hostedtoolcache/go/1.18.3/x64/src/bytes/buffer.go:204 +0x94
crypto/tls.(*Conn).readFromUntil(0x140007ab180, {0x12cb25ea0?, 0x1400000e800}, 0x1024a81ec?)
	/opt/hostedtoolcache/go/1.18.3/x64/src/crypto/tls/conn.go:807 +0xd8
crypto/tls.(*Conn).readRecordOrCCS(0x140007ab180, 0x0)
	/opt/hostedtoolcache/go/1.18.3/x64/src/crypto/tls/conn.go:614 +0xdc
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.18.3/x64/src/crypto/tls/conn.go:582
crypto/tls.(*Conn).Read(0x140007ab180, {0x140000b6000, 0x1000, 0x1028c776c?})
	/opt/hostedtoolcache/go/1.18.3/x64/src/crypto/tls/conn.go:1285 +0x180
bufio.(*Reader).Read(0x1400009c480, {0x140002fc820, 0x9, 0x1028c70fc?})
	/opt/hostedtoolcache/go/1.18.3/x64/src/bufio/bufio.go:236 +0x1e4
io.ReadAtLeast({0x10426dc48, 0x1400009c480}, {0x140002fc820, 0x9, 0x9}, 0x9)
	/opt/hostedtoolcache/go/1.18.3/x64/src/io/io.go:331 +0xa4
io.ReadFull(...)
	/opt/hostedtoolcache/go/1.18.3/x64/src/io/io.go:350
net/http.http2readFrameHeader({0x140002fc820?, 0x9?, 0x14000a263c0?}, {0x10426dc48?, 0x1400009c480?})
	/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/h2_bundle.go:1566 +0x5c
net/http.(*http2Framer).ReadFrame(0x140002fc7e0)
	/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/h2_bundle.go:1830 +0x84
net/http.(*http2clientConnReadLoop).run(0x14000a74f88)
	/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/h2_bundle.go:8815 +0x100
net/http.(*http2ClientConn).readLoop(0x1400085e600)
	/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/h2_bundle.go:8711 +0x60
created by net/http.(*http2Transport).newClientConn
	/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/h2_bundle.go:7439 +0x924
```

### Expected behavior

flytectl shouldn't crash

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by YasmineHamdy** [comment]
I am using Intel Mac and I have the same issue.

**Comment by pmahindrakar-oss** [comment]
@YasmineHamdy , i have a [PR](https://github.com/flyteorg/flytectl/pull/342) out and that seems to have fixed the issue. I think the issue arises with kube context  file of the user and if it contains a particular map structural data which hits reflect_map then we run into this issue and not specific to M1. 

The utility function in apimachinery iterates over all the values in the kube context and writes them back with the updated context of the flyte sandbox.

I am removing that from description. If you want to try it out then you can use the PR and make compile to get the binary bin/flytectl until this is merged and released

**Comment by YasmineHamdy** [comment]
@pmahindrakar-oss, thank you a lot.
