### ISSUE TITLE
[BUG] Error creating resource server 404 Not Found

### ISSUE THREAD

**Issue by joaoloboguerra** [flyteorg/flyte#3384]
### Describe the bug

Hi everyone. 

Anybody could be help me with error?
This erros is ocorred  now in pod flyteadmin

`goroutine 1 [running]:
main.main()
	/go/src/github.com/flyteorg/flyteadmin/cmd/main.go:13 +0x91
time="2023-03-01T13:28:54Z" level=info msg="Using config file: [/etc/flyte/config/cluster_resources.yaml /etc/flyte/config/db.yaml /etc/flyte/config/domain.yaml /etc/flyte/config/logger.yaml /etc/flyte/config/server.yaml /etc/flyte/config/storage.yaml /etc/flyte/config/task_resource_defaults.yaml]"
{"json":{"src":"service.go:263"},"level":"error","msg":"Error creating resource server 404 Not Found: ","ts":"2023-03-01T13:28:56Z"}
Error: 404 Not Found: 
Usage:
  flyteadmin serve [flags]`

in website I got error

Failed to fetch data
Request failed with status code 503

### Expected behavior

I don't know whats happen, anybody help me?

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@joaoloboguerra , can you provide repro steps for this?
