### ISSUE TITLE
[BUG] Runtime error causes retries

### ISSUE THREAD

**Issue by gregfriedland** [flyteorg/flyte#3606]
### Describe the bug

When a task fails with a user-generated `RuntimeError`, the workflow is retried. According to the [docs](https://docs.flyte.org/projects/flytekit/en/latest/design/authoring.html#exception-handling), it seems like this case is considered non-recoverable and should not be retried.

### Expected behavior

Workflow and task fail with no retries

### Screenshots

Traceback (most recent call last):

      File "/app/pip_pypi__flytekit/flytekit/exceptions/scopes.py", line 203, in user_entry_point
        return wrapped(*args, **kwargs)
      File "/app/atomwise/...", line 266, in run_block
        block.validate_output(cmpds, result)
      File "/app/atomwise/..., line 119, in validate_output
        raise RuntimeError(

Message:

    <blah>

User error.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by gregfriedland** [comment]
FYI I was asked to file this issue by @pingsutw

**Comment by gregfriedland** [comment]
It looks related to nested tasks. Here's a repro:

`test_wf.py`
```
# Third party
from flytekit import dynamic


@dynamic
def run_wf(a: int) -> int:
    return nested_wf(a=a)


@dynamic
def nested_wf(a: int) -> int:
    if a == 1:
        raise RuntimeError()
    return a + 1
```

`exec.py`
```
# Third party
from flytekit.configuration import Config
from flytekit.remote import FlyteRemote
from flytekit.remote.executions import FlyteWorkflowExecution

# Atomwise
from test_wf import run_wf

FLYTE_CONFIG = Config.auto("flytekit.config")
TEST_S3_BUCKET = "s3://atomwise-test-bucket/flyte"

remote = FlyteRemote(
    config=FLYTE_CONFIG,
    default_project="lego",
    default_domain="development",
    data_upload_location=TEST_S3_BUCKET,
)

execution: FlyteWorkflowExecution = (
    remote.execute(
        run_wf,
        inputs={"a": 1},
        wait=True,
        project="lego",
        domain="development",
    ),
)

print(execution)
```

```
$ pyflyte register --project x --domain development test_wf.py
Running pyflyte register ...
Successfully registered 2 entities

$ python exec.py
...
closure {
  error {
    code: "RetriesExhausted|USER:Unknown"
    message: "[4/4] currentAttempt done. Last Error: USER::Traceback (most recent call last):\n\n      File \"/usr/local/lib/python3.9/site-packages/flytekit/exceptions/scopes.py\", line 203, in user_entry_point\n        return wrapped(*args, **kwargs)\n      File \"/root/test_wf.py\", line 13, in nested_wf\n        raise RuntimeError()\n\nMessage:\n\n    \n\nUser error."
    kind: USER
```
