### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by gabrielmolinah** [flyteorg/flyte#3687]
### Describe the bug

Hi!
This is such a great project, 
i'm having problems when i add 
"from flytekitplugins.spark import Spark" to my *.py
after running (remote way, im not having problems using 'pyflyte run *.py my_wf) the process is complete, but the wokflow appears failed with the following message:

[1/1] currentAttempt done. Last Error: USER::trap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/flyte.py", line 5, in <module>
    from flytekitplugins.spark import Spark
ModuleNotFoundError: No module named 'flytekitplugins.spark'
Traceback (most recent call last):
  File "/usr/local/bin/pyflyte-fast-execute", line 8, in <module>
    sys.exit(fast_execute_task_cmd())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flytekit/bin/entrypoint.py", line 507, in fast_execute_task_cmd
    subprocess.run(cmd, check=True)
  File "/usr/local/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pyflyte-execute', '--inputs', 's3://my-s3-bucket/metadata/propeller/flytesnacks-development-fb2b24912c18b4fe8ad6/n0/data/inputs.pb', '--output-prefix', 's3://my-s3-bucket/metadata/propeller/flytesnacks-development-fb2b24912c18b4fe8ad6/n0/data/0', '--raw-output-data-prefix', 's3://my-s3-bucket/data/jt/fb2b24912c18b4fe8ad6-n0-0', '--checkpoint-path', 's3://my-s3-bucket/data/jt/fb2b24912c18b4fe8ad6-n0-0/_flytecheckpoints', '--prev-checkpoint', '""', '--dynamic-addl-distro', 's3://my-s3-bucket/flytesnacks/development/JRL5SKCU57N5WRXTICZXVDEUGY======/scriptmode.tar.gz', '--dynamic-dest-dir', '/root', '--resolver', 'flytekit.core.python_auto_container.default_task_resolver', '--', 'task-module', 'flyte', 'task-name', 'say_hello']' returned non-zero exit status 1.

Can you please help me?

### Expected behavior

i expect to run without error when i add '--remote' flag 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
Need more details. Our guess is that the image doesn't contain spark.

**Comment by davidmirror-ops** [comment]
Support has been provided (see [thread](https://flyte-org.slack.com/archives/CP2HDHKE1/p1684250036718499)) and additional follow up offered. Original problem solved using `ImageSpec`. Remaining problems not related
