### ISSUE TITLE
[BUG] Can't create project from file in demo

### ISSUE THREAD

**Issue by rupurt** [flyteorg/flyte#3744]
### Describe the bug

Given a `flyte` demo cluster
When I try to create a project from a file
Then it should be created in the `demo` cluster
But it currently panics with an invalid memory address

```sh
> flytectl create project --file ./flyte/projects/myproject.yaml
INFO[0000] [0] Couldn't find a config file []. Relying on env vars and pflags.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x147b463]

goroutine 1 [running]:
github.com/flyteorg/flytectl/cmd/core.CommandContext.AdminClient(...)
        /home/runner/work/flytectl/flytectl/cmd/core/cmd_ctx.go:57
github.com/flyteorg/flytectl/cmd/create.createProjectsCommand({0x2563718, 0xc00005c228}, {0xc000ec5b40?, 0x100000049c165?, 0x25633c0?}, {0x0, {0x0, 0x0}, {0x0, 0x0}, ...})
        /home/runner/work/flytectl/flytectl/cmd/create/project.go:62 +0xe3
github.com/flyteorg/flytectl/cmd/core.generateCommandFunc.func1(0xc000af2f00?, {0xc000a41620, 0x0, 0x2})
        /home/runner/work/flytectl/flytectl/cmd/core/cmd.go:70 +0x93d
github.com/spf13/cobra.(*Command).execute(0xc000af2f00, {0xc000a41600, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000a6e780)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/flyteorg/flytectl/cmd.ExecuteCmd()
        /home/runner/work/flytectl/flytectl/cmd/root.go:137 +0x1e
main.main()
        /home/runner/work/flytectl/flytectl/main.go:12 +0x1d

```

### Expected behavior

A project to be created from the file

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
i have done this multiple times, i think this is old and works now
