### ISSUE TITLE
[BUG] undefined optional argument in a dynamic task is a `Promise`, should be `None`

### ISSUE THREAD

**Issue by alekpikl** [flyteorg/flyte#3831]
### Describe the bug

An empty `Optional[SomeType] = None` argument in a `dynamic` task is a `Promise` during execution.

A reproducer:

```python
from typing import Optional

from flytekit import dynamic, workflow


@dynamic
def my_task(opt: Optional[int] = None):
    print(opt)  # Promise(node:.opt)


@workflow
def workflow():
    my_task()
```

In `my_task,` `opt` is a `Promise(node:.opt).`

**Works as expected locally but not in a cluster.**

### Expected behavior

The argument should be `None` during execution.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by alekpikl** [comment]
Another reproducer that fails with 
```python
[1/1] currentAttempt done. Last Error: USER::Traceback (most recent call last):

      File "/opt/pyenv-root/versions/3.9.16/lib/python3.9/site-packages/flytekit/exceptions/scopes.py", line 206, in user_entry_point
        return wrapped(*args, **kwargs)
      File "/home/flyte/.../scripts/reproduce.py", line 13, in my_task
        print(f"My tensor shape: {ten.shape=}")

Message:

    'Promise' object has no attribute 'shape'

User error.
```


```python
import torch
from flytekit import PythonFunctionTask, dynamic, task, workflow


@task
def get_ten() -> torch.Tensor:
    return torch.rand(2)

@dynamic()
def my_task(get_ten: PythonFunctionTask = get_ten):
    ten = get_ten()
    print(f"My tensor shape: {ten.shape=}")


@dynamic()
def my_dyn(get_ten: PythonFunctionTask = get_ten):
    my_task(get_ten=get_ten)

@workflow
def my_work():
    my_dyn(get_ten=get_ten)


if __name__ == '__main__':
    my_work()
```

**Comment by TaiJuWu** [comment]
@alekpikl your first case shows None for me.
Is this your command?
<img width="407" alt="image" src="https://github.com/flyteorg/flyte/assets/33004323/60c5d0d2-33c3-4fe9-886e-e096c747baf0">

**Comment by alekpikl** [comment]
Closing because I couldn't reproduce. Probably something was wrong with my setup.
