### ISSUE TITLE
[BUG] flytescheduler crashes with "panic: runtime error: slice bounds out of range [1:0]"

### ISSUE THREAD

**Issue by givanovexpe** [flyteorg/flyte#4242]
### Describe the bug

The latest flytescheduler 1.9.18 crashes when running for more than 2 days. The problem looks like related to okta authentication (that's what the stack trace points to). After two days the pod crashed and when into a CrashLoopBackOff with the init container (flytescheduler-check). Initially the pod started just fine. 

This is the stack trace of the flytescheduler-check after it started crashing.

```
time="2023-10-16T13:31:44Z" level=info msg="Using config file: [/etc/flyte/config/admin.yaml /etc/flyte/config/db.yaml /etc/flyte/config/logger.yaml /etc/flyte/config/server.yaml]"
{"json":{"src":"viper.go:398"},"level":"debug","msg":"Config section [remotedata] updated. No update handler registered.","ts":"2023-10-16T13:31:44Z"}
{"json":{"src":"viper.go:398"},"level":"debug","msg":"Config section [notifications] updated. No update handler registered.","ts":"2023-10-16T13:31:44Z"}
{"json":{"src":"viper.go:398"},"level":"debug","msg":"Config section [cloudevents] updated. No update handler registered.","ts":"2023-10-16T13:31:44Z"}
{"json":{"src":"viper.go:398"},"level":"debug","msg":"Config section [clusterpools] updated. No update handler registered.","ts":"2023-10-16T13:31:44Z"}
{"json":{"src":"viper.go:398"},"level":"debug","msg":"Config section [qualityofservice] updated. No update handler registered.","ts":"2023-10-16T13:31:44Z"}
{"json":{"src":"viper.go:398"},"level":"debug","msg":"Config section [task_resources] updated. No update handler registered.","ts":"2023-10-16T13:31:44Z"}
{"json":{"src":"client.go:63"},"level":"info","msg":"Initialized Admin client","ts":"2023-10-16T13:31:44Z"}
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/flyteorg/flyte/flyteidl/clients/go/admin/externalprocess.Execute({0x38bae50?, 0x8?, 0x7f9481ecc5b8?})
	/go/src/github.com/flyteorg/flyteidl/clients/go/admin/externalprocess/command_executor.go:6 +0x68
github.com/flyteorg/flyte/flyteidl/clients/go/admin.ExternalTokenSourceProvider.GetTokenSource({{0x38bae50?, 0x40dd07?, 0x18?}}, {0x1f3cee0?, 0x7f945a27b901?})
	/go/src/github.com/flyteorg/flyteidl/clients/go/admin/token_source_provider.go:119 +0x25
github.com/flyteorg/flyte/flyteidl/clients/go/admin.GetProxyTokenSource({0x26c8228, 0xc0000fd800}, 0x9d83d7?)
	/go/src/github.com/flyteorg/flyteidl/clients/go/admin/auth_interceptor.go:59 +0x9d
github.com/flyteorg/flyte/flyteidl/clients/go/admin.MaterializeProxyAuthCredentials({0x26c8228?, 0xc0000fd800?}, 0xc0008d5180, 0x26c8228?)
	/go/src/github.com/flyteorg/flyteidl/clients/go/admin/auth_interceptor.go:67 +0x3a
github.com/flyteorg/flyte/flyteidl/clients/go/admin.NewProxyAuthInterceptor.func1({0x26c8228, 0xc0000fd800}, {0x22113d4, 0x1c}, {0x1f9ee80, 0xc000909480}, {0x1f9ef40, 0xc0015229f0}, 0x8?, 0x2314348, ...)
	/go/src/github.com/flyteorg/flyteidl/clients/go/admin/auth_interceptor.go:165 +0xe6
google.golang.org/grpc.getChainUnaryInvoker.func1({0x26c8228, 0xc0000fd800}, {0x22113d4, 0x1c}, {0x1f9ee80, 0xc000909480}, {0x1f9ef40, 0xc0015229f0}, 0xc0018ad740?, {0x0, ...})
	/go/pkg/mod/google.golang.org/grpc@v1.56.1/clientconn.go:507 +0x154
github.com/grpc-ecosystem/go-grpc-middleware/retry.UnaryClientInterceptor.func1({0x26c8260, 0xc001522a80}, {0x22113d4, 0x1c}, {0x1f9ee80, 0xc000909480}, {0x1f9ef40, 0xc0015229f0}, 0xc0018ad828?, 0xc001522de0, ...)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/retry/retry.go:44 +0x2c9
google.golang.org/grpc.getChainUnaryInvoker.func1({0x26c8260, 0xc001522a80}, {0x22113d4, 0x1c}, {0x1f9ee80, 0xc000909480}, {0x1f9ef40, 0xc0015229f0}, 0xc0009f8101?, {0x0, ...})
	/go/pkg/mod/google.golang.org/grpc@v1.56.1/clientconn.go:507 +0x154
github.com/grpc-ecosystem/go-grpc-prometheus.(*ClientMetrics).UnaryClientInterceptor.func1({0x26c8260, 0xc001522a80}, {0x22113d4, 0x1c}, {0x1f9ee80, 0xc000909480}, {0x1f9ef40, 0xc0015229f0}, 0x38bae50?, 0xc001522ae0, ...)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/client_metrics.go:112 +0x117
google.golang.org/grpc.getChainUnaryInvoker.func1({0x26c8260, 0xc001522a80}, {0x22113d4, 0x1c}, {0x1f9ee80, 0xc000909480}, {0x1f9ef40, 0xc0015229f0}, 0x7f945a2c5840?, {0x0, ...})
	/go/pkg/mod/google.golang.org/grpc@v1.56.1/clientconn.go:507 +0x154
github.com/flyteorg/flyte/flyteidl/clients/go/admin.NewAuthInterceptor.func1({0x26c81f0?, 0xc000060030?}, {0x22113d4, 0x1c}, {0x1f9ee80, 0xc000909480}, {0x1f9ef40, 0xc0015229f0}, 0x203000?, 0xc001522a20, ...)
	/go/src/github.com/flyteorg/flyteidl/clients/go/admin/auth_interceptor.go:138 +0x12e
google.golang.org/grpc.chainUnaryClientInterceptors.func1({0x26c81f0, 0xc000060030}, {0x22113d4, 0x1c}, {0x1f9ee80, 0xc000909480}, {0x1f9ef40, 0xc0015229f0}, 0x7f9481ecc108?, 0x2314348, ...)
	/go/pkg/mod/google.golang.org/grpc@v1.56.1/clientconn.go:495 +0x128
google.golang.org/grpc.(*ClientConn).Invoke(0xc0018b7800, {0x26c81f0, 0xc000060030}, {0x22113d4, 0x1c}, {0x1f9ee80, 0xc000909480}, {0x1f9ef40, 0xc0015229f0}, {0x0, ...})
	/go/pkg/mod/google.golang.org/grpc@v1.56.1/call.go:40 +0x24d
google.golang.org/grpc/health/grpc_health_v1.(*healthClient).Check(0xc000257810, {0x26c81f0, 0xc000060030}, 0x26c81f0?, {0x0, 0x0, 0x0})
	/go/pkg/mod/google.golang.org/grpc@v1.56.1/health/grpc_health_v1/health_grpc.pb.go:78 +0xce
github.com/flyteorg/flyte/flyteadmin/cmd/scheduler/entrypoints.glob..func1(0x3861d80?, {0x21e0a36?, 0x2?, 0x2?})
	/go/src/github.com/flyteorg/flyteadmin/cmd/scheduler/entrypoints/precheck.go:32 +0x1a2
github.com/spf13/cobra.(*Command).execute(0x3861d80, {0xc00095aa60, 0x2, 0x2})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x3862000)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/flyteorg/flyte/flyteadmin/cmd/scheduler/entrypoints.Execute()
	/go/src/github.com/flyteorg/flyteadmin/cmd/scheduler/entrypoints/root.go:39 +0x25
main.main()
	/go/src/github.com/flyteorg/flyteadmin/cmd/scheduler/main.go:10 +0x77
```

```
cat admin.yaml
admin:
  clientId: <cliendIt>
  clientSecretLocation: /vault/secrets/client_secret
  endpoint: flyteadmin:81
  insecure: true
event:
  capacity: 1000
  rate: 500
  type: admin
```

I believe the issue might lie in Okta, as I am using the free dev tier of Okta. Auth is setup in okta and flyte and I am able to login to the console and submit jobs via flyteadmin. However I believe there may be a problem with refresh tokens and I believe the bug above may be related to the inability of flytescheduler to use refresh tokens to get a new access token.

### Expected behavior

flytescheduler not crashing.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@givanovexpe , this was fixed in https://github.com/flyteorg/flyte/commit/2edc3bd552b559d250bfff77987506da586a1759. Can you try again with the 1.9.22 or newer images?

**Comment by givanovexpe** [comment]
I checked with 1.9.26 and I think it's fixed. Thanks.
