### ISSUE TITLE
[BUG] flytekitplugins_envd for windows 11?

### ISSUE THREAD

**Issue by andife** [flyteorg/flyte#4827]
### Describe the bug

Hello,
I wanted to install flytekitplugins_envd in my conda-env (python 3.10) and the install process with pip failed. (Should that work?)

```
(flyte) C:\dev\my_project2>pip install flytekitplugins_envd==1.10.3
Collecting flytekitplugins_envd==1.10.3
  Using cached flytekitplugins_envd-1.10.3-py3-none-any.whl.metadata (932 bytes)
Requirement already satisfied: flytekit in c:\users\andreas\miniforge3\envs\flyte\lib\site-packages (from flytekitplugins_envd==1.10.3) (1.10.3)
Collecting envd (from flytekitplugins_envd==1.10.3)
  Using cached envd-0.3.45.tar.gz (333 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      WARNING:root:.GIT_TAG_INFO not found
      Traceback (most recent call last):
        File "<string>", line 37, in build_envd_if_not_found
        File "C:\Users\andreas\miniforge3\envs\flyte\lib\subprocess.py", line 345, in call
          with Popen(*popenargs, **kwargs) as p:
        File "C:\Users\andreas\miniforge3\envs\flyte\lib\subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\andreas\miniforge3\envs\flyte\lib\subprocess.py", line 1456, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\andreas\miniforge3\envs\flyte\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\andreas\miniforge3\envs\flyte\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\andreas\miniforge3\envs\flyte\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\andreas\AppData\Local\Temp\pip-build-env-2gopd5ea\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\andreas\AppData\Local\Temp\pip-build-env-2gopd5ea\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\andreas\AppData\Local\Temp\pip-build-env-2gopd5ea\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 103, in <module>
        File "<string>", line 78, in get_version
        File "<string>", line 43, in build_envd_if_not_found
        File "C:\Users\andreas\miniforge3\envs\flyte\lib\subprocess.py", line 345, in call
          with Popen(*popenargs, **kwargs) as p:
        File "C:\Users\andreas\miniforge3\envs\flyte\lib\subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\andreas\miniforge3\envs\flyte\lib\subprocess.py", line 1456, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Does this relate to https://github.com/tensorchord/envd/issues/1550 ?

### Expected behavior

just work

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pingsutw** [comment]
@kemingy does `envd` support windows 11?

**Comment by kemingy** [comment]
> @kemingy does `envd` support windows 11?

`envd` doesn't have a Windows release. I haven't tried to compile in Windows. It's recommended to use WSL.
