### ISSUE TITLE
[BUG] flytectl panics when wrong config path is passed

### ISSUE THREAD

**Issue by debajyoti-truefoundry** [flyteorg/flyte#4891]
### Describe the bug

```
❯ flytectl version
INFO[0000] [0] Couldn't find a config file []. Relying on env vars and pflags.

 A new release of flytectl is available: 0.8.11 → v0.8.12
To upgrade, run: brew update && brew upgrade flytectl
https://github.com/flyteorg/flytectl/releases/tag/v0.8.12

{
  "App": "flytectl",
  "Build": "71fbaf4",
  "Version": "0.8.11",
  "BuildTime": "2024-02-13 22:09:28.318664 +0530 IST m=+0.027465309"
}
pipelines/flyte/my_workflow on  main [$!?⇡] via 🐍 v3.11.7 (venv)
❯ flytectl --config config.yaml update launchplan --project flytesnacks --domain development --deactivate train-cron --version 1707840433
INFO[0000] [0] Couldn't find a config file []. Relying on env vars and pflags.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x28af821]

goroutine 1 [running]:
github.com/flyteorg/flytectl/cmd/core.CommandContext.AdminClient(...)
        /home/runner/work/flytectl/flytectl/cmd/core/cmd_ctx.go:57
github.com/flyteorg/flytectl/cmd/update.updateLPFunc({0x33da9d8, 0xc000054068}, {0xc00094f5e0, 0x1, 0x33da680?}, {0x0, {0x0, 0x0}, {0x0, 0x0}, ...})
        /home/runner/work/flytectl/flytectl/cmd/update/launch_plan.go:76 +0x381
github.com/flyteorg/flytectl/cmd/core.generateCommandFunc.func1(0xc0005a9900?, {0xc00094f5e0, 0x1, 0xa})
        /home/runner/work/flytectl/flytectl/cmd/core/cmd.go:70 +0x93d
github.com/spf13/cobra.(*Command).execute(0xc0005a9900, {0xc00094f360, 0xa, 0xa})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0005e8f00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/flyteorg/flytectl/cmd.ExecuteCmd()
        /home/runner/work/flytectl/flytectl/cmd/root.go:160 +0x1e
main.main()
        /home/runner/work/flytectl/flytectl/main.go:12 +0x1d
```

### Expected behavior

It will not panic.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Terryhung** [comment]
#take

**Comment by Terryhung** [comment]
I found that the root cause is our failure to return an error when the config file is missing. As a result, errors occur when certain commands require the config. I’d like to understand why we chose not to return an error for an empty or missing config file—is there a specific reason for this?

Related:
[code1](https://github.com/flyteorg/flyte/blob/master/flytestdlib/config/viper/viper.go#L138)
[code2](https://github.com/flyteorg/flyte/blob/master/flytestdlib/config/viper/viper.go#L147)

**Comment by eapolinario** [comment]
Reverting https://github.com/flyteorg/flyte/pull/6100 for now as this is causing issues for users and in CI in a bunch of our repos (e.g. https://github.com/flyteorg/flytekit/actions/runs/12266004823/job/34223269731?pr=2995).

This change went out in flytectl 0.9.3. I'm looking into how to remove that release once a new version containing the revert is published.
