### ISSUE TITLE
[BUG] flytekitplugins-pydantic errors when a pydantic class is used as an input on the main workflow called remotely. 

### ISSUE THREAD

**Issue by artgramlich** [flyteorg/flyte#5236]
### Describe the bug

When a workflow contains an input that is a Pydantic type, calling the workflow remotely errors with due to a None type. This does not happen when the workflow is run locally or in a when a Pydantic type is an input parameter in a subworkflow or task.

Some simple debugging shows that the error originates in the flytekitplugins/pydantic/basemodel_transformer.py in the to_python_value on this bit of code:

```basemodel_literals: BaseModelLiterals = lv.map.literals```

with lv.map being None.

### Expected behavior

When a workflow input is a Pydantic type, that the type is unmarshalled from json into the Pydantic type.

### Additional context to reproduce

I've created a public repo with a simple test case that triggers this at https://github.com/artgramlich/flyte-complex-types-problem and am attaching a zip of the code. This repo/code also contains some patched files that show the lower level error that causes the issue.

[flyte-complex-types-problem-main.zip](https://github.com/flyteorg/flyte/files/14985220/flyte-complex-types-problem-main.zip)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by artgramlich** [comment]
In the example attached, the environments are the same.  The actual error is:

`
[3/3] currentAttempt done. Last Error: SYSTEM::Traceback (most recent call last):

      File "/opt/venv/lib/python3.12/site-packages/flytekit/exceptions/scopes.py", line 178, in system_entry_point
        return wrapped(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/venv/lib/python3.12/site-packages/flytekit/core/base_task.py", line 669, in dispatch_execute
        raise type(exc)(msg) from exc

Message:

    AttributeError: Failed to convert inputs of task 'workflows.example.say_hello_complex':
  'NoneType' object has no attribute 'literals'

`

Do some patching so the the underlying error is logged shows that it is caused by a null value. 

`
[3/3] currentAttempt done. Last Error: SYSTEM::Traceback (most recent call last):

      File "/opt/venv/lib/python3.12/site-packages/flytekit/exceptions/scopes.py", line 178, in system_entry_point
        return wrapped(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/venv/lib/python3.12/site-packages/flytekit/core/base_task.py", line 745, in dispatch_execute
        raise exc
      File "/opt/venv/lib/python3.12/site-packages/flytekit/core/base_task.py", line 741, in dispatch_execute
        native_inputs = self._literal_map_to_python_input(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/venv/lib/python3.12/site-packages/flytekit/core/base_task.py", line 603, in _literal_map_to_python_input
        return TypeEngine.literal_map_to_kwargs(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/venv/lib/python3.12/site-packages/flytekit/core/utils.py", line 309, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/opt/venv/lib/python3.12/site-packages/flytekit/core/type_engine.py", line 1195, in literal_map_to_kwargs
        kwargs[k] = TypeEngine.to_python_value(ctx, lm.literals[k], python_interface_inputs[k])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/venv/lib/python3.12/site-packages/flytekit/core/type_engine.py", line 1140, in to_python_value
        return transformer.to_python_value(ctx, lv, expected_python_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/venv/lib/python3.12/site-packages/flytekitplugins/pydantic/basemodel_transformer.py", line 70, in to_python_value
        basemodel_literals: BaseModelLiterals = lv.map.literals
                                                ^^^^^^^^^^^^^^^

Message:

    AttributeError: 'NoneType' object has no attribute 'literals'

SYSTEM ERROR! Contact platform administrators.
`

**Comment by ai-rnatour** [comment]
We're also seeing this error on `1.10.7` `1.12.0`. Here's a minimal example:
```python
from flytekit import dynamic, task, workflow
from pydantic import BaseModel, PositiveInt


class Foo(BaseModel):
    x: PositiveInt


@task
def say_hello(*, foo: Foo) -> str:
    msg = f"Hello, {foo.x}!"
    print(msg)
    print(type(foo.x))
    return msg


@dynamic
def _say_hello_wf(*, foo: Foo) -> str:
    return say_hello(foo=foo)


@workflow
def say_hello_wf(*, foo: Foo) -> str:
    return _say_hello_wf(foo=foo)
```

I have tried this with `pydantic` 2.x (making sure to import the `v1` BaseModel) and 1.x.
