### ISSUE TITLE
[BUG] Task should not attempt to retry if fails to deserialize the input

### ISSUE THREAD

**Issue by pingsutw** [flyteorg/flyte#5439]
### Describe the bug

Flyte relaunches a new task when flytekit failed to deserialize the input
```bash
Traceback (most recent call last):

      File "/usr/local/lib/python3.12/site-packages/flytekit/exceptions/scopes.py", line 183, in system_entry_point
        return wrapped(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.12/site-packages/flytekit/core/base_task.py", line 701, in dispatch_execute
        raise type(exc)(msg) from exc

Message:

    FileNotFoundError: Failed to convert inputs of task 'image-moderation.src.fetch_images.fetch_images':
  [Errno 2] No such file or directory: '/tmp/flyte-6j8s0f7x/raw/557cfc528c40ae92c7c7a199f162b51c/a0ec49912229432d8e6622c907047e4d'

SYSTEM ERROR! Contact platform administrators.

```

### Expected behavior

Task shouldn't retry in this case

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
We've been talking about simplifying error handling in flytekit as a potential project, so tagging this one with `Improve error handling`.

**Comment by Future-Outlier** [comment]
done by @pingsutw
