### ISSUE TITLE
[BUG] Setting `cache=True` on a task seems to break unit tests

### ISSUE THREAD

**Issue by shashank-lgtm** [flyteorg/flyte#5657]
I'm using `flytekit.core.testing.task_mock` and it seems to work well for testing my workflows. However, if I enable caching for any task of the workflow, it gives me the following exception trace:

```
Traceback (most recent call last):
  File "python_deps_flytekit/site-packages/flytekit/core/workflow.py", line 294, in __call__
    raise exc
  File "python_deps_flytekit/site-packages/flytekit/core/workflow.py", line 287, in __call__
    return flyte_entity_call_handler(self, *args, **input_kwargs)
  File "python_deps_flytekit/site-packages/flytekit/core/promise.py", line 1212, in flyte_entity_call_handler
    result = cast(LocallyExecutable, entity).local_execute(child_ctx, **kwargs)
  File "python_deps_flytekit/site-packages/flytekit/core/workflow.py", line 313, in local_execute
    function_outputs = self.execute(**kwargs_literals)
  File "python_deps_flytekit/site-packages/flytekit/core/workflow.py", line 797, in execute
    return exception_scopes.user_entry_point(self._workflow_function)(**kwargs)
  File "python_deps_flytekit/site-packages/flytekit/exceptions/scopes.py", line 148, in f
    return outer_f(inner_f, args, kwargs)
  File "python_deps_flytekit/site-packages/flytekit/exceptions/scopes.py", line 219, in user_entry_point
    raise exc.type(f"Error encountered while executing '{fn_name}':\n  {exc.value}") from exc
OSError: Error encountered while executing 'workflow':
  [Errno 30] Cache directory "/$HOME/.flyte/local-cache" does not exist and could not be created
```

**Comment by shashank-lgtm** [comment]
Setting the environment variable fixed the issue.
