### ISSUE TITLE
[BUG]  flytekitplugin-deck-standard misses critical runtime depencies

### ISSUE THREAD

**Issue by fellhorn** [flyteorg/flyte#5792]
### Describe the bug

https://github.com/flyteorg/flytekit/pull/2766 removed `plotly` and others from the list of hard dependencies and turned them into soft dependencies.

Because of this a minimal installation of `flytekit` and `flytekitplugins-deck-standard` is now broken:

```sh
> uv pip install flytekitplugins-deck-standard==1.13.6
> python -c 'import flytekit'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dennis/.pyenv/versions/3.12/lib/python3.12/site-packages/flytekit/__init__.py", line 317, in <module>
    load_implicit_plugins()
  File "/home/dennis/.pyenv/versions/3.12/lib/python3.12/site-packages/flytekit/__init__.py", line 313, in load_implicit_plugins
    p.load()
  File "/home/dennis/.pyenv/versions/3.12.6/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dennis/.pyenv/versions/3.12.6/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dennis/.pyenv/versions/3.12/lib/python3.12/site-packages/flytekitplugins/deck/__init__.py", line 19, in <module>
    from .renderer import (
  File "/home/dennis/.pyenv/versions/3.12/lib/python3.12/site-packages/flytekitplugins/deck/renderer.py", line 17, in <module>
    px = lazy_module("plotly.express")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dennis/.pyenv/versions/3.12/lib/python3.12/site-packages/flytekit/lazy_import/lazy_module.py", line 36, in lazy_module
    spec = importlib.util.find_spec(fullname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib.util>", line 91, in find_spec
ModuleNotFoundError: No module named 'plotly'
```

After installing `pandas` and `plotly` manually, there is no more `ModuleNotFoundError` or `ImportError`.

### Expected behavior

A simple `import flytekit` should work out of the box, a minimal function path for deck as well.

Other code paths can require extra dependencies, that might be "soft deps". These should ideally be extra targets for a simplified installation and to clearly list these.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Future-Outlier** [comment]
Hi, @fellhorn 
Thank you for reporting this bug
