### ISSUE TITLE
[BUG] Task fails if empty list is passed as argument

### ISSUE THREAD

**Issue by filippobrizzi** [flyteorg/flyte#918]
**Describe the bug**
Task fails to run if empty list is passed as argument.

Take this task
```py
@flytekit.task
def test_empty_list(
    name: str,
    list_of_stuff: List[str],
) -> int:
    return len(list_of_stuff)
```
if executed on Flyte (not locally), by passing an empty list to `list_of_stuff`, it will fail with the following error:

```
[4/4] currentAttempt done. Last Error: USER::Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/flyte-workflows-104TnIye-py3.8/lib/python3.8/site-packages/flytekit/bin/entrypoint.py", line 94, in _dispatch_execute
    outputs = task_def.dispatch_execute(ctx, idl_input_literals)
  File "/root/.cache/pypoetry/virtualenvs/flyte-workflows-104TnIye-py3.8/lib/python3.8/site-packages/flytekit/core/base_task.py", line 402, in dispatch_execute
    native_inputs = TypeEngine.literal_map_to_kwargs(exec_ctx, input_literal_map, self.python_interface.inputs)
  File "/root/.cache/pypoetry/virtualenvs/flyte-workflows-104TnIye-py3.8/lib/python3.8/site-packages/flytekit/core/type_engine.py", line 297, in literal_map_to_kwargs
    return {k: TypeEngine.to_python_value(ctx, lm.literals[k], v) for k, v in python_types.items()}
  File "/root/.cache/pypoetry/virtualenvs/flyte-workflows-104TnIye-py3.8/lib/python3.8/site-packages/flytekit/core/type_engine.py", line 297, in <dictcomp>
    return {k: TypeEngine.to_python_value(ctx, lm.literals[k], v) for k, v in python_types.items()}
  File "/root/.cache/pypoetry/virtualenvs/flyte-workflows-104TnIye-py3.8/lib/python3.8/site-packages/flytekit/core/type_engine.py", line 275, in to_python_value
    return transformer.to_python_value(ctx, lv, expected_python_type)
  File "/root/.cache/pypoetry/virtualenvs/flyte-workflows-104TnIye-py3.8/lib/python3.8/site-packages/flytekit/core/type_engine.py", line 342, in to_python_value
    return [TypeEngine.to_python_value(ctx, x, st) for x in lv.collection.literals]
AttributeError: 'NoneType' object has no attribute 'literals'
```

**Expected behavior**
The task should return `0`

***Screenshots***
![image](https://user-images.githubusercontent.com/5880013/114861639-ce5ddd00-9ded-11eb-95bf-25bba1e32de0.png)

**Comment by fediazgon** [comment]
In the latest version is working with empty lists but not with empty dictionaries. I will take a look.
