### ISSUE TITLE
[Flytectl Feature] Supporting registration of fast serialized files

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#939]
**Describe the feature/command for flytectl**
Currently flytectl only supports registering files which have been serialized using regular serialize.

which runs the following command during execution . Following is copy of the args to the pod.

The files were serialized and then registered using flytectl and later executed also using flytectl

Following execution works.
```
Args:
      pyflyte-execute
      --inputs
      s3://my-s3-bucket/metadata/propeller/flytectldemo-development-f64034cd32f544af2b79/n0/data/inputs.pb
      --output-prefix
      s3://my-s3-bucket/metadata/propeller/flytectldemo-development-f64034cd32f544af2b79/n0/data/0
      --raw-output-data-prefix
      s3://lyft-modelbuilder/cookbook/us/f64034cd32f544af2b79-n0-0
      --resolver
      flytekit.core.python_auto_container.default_task_resolver
      --
      task-module
      core.remote_flyte.customizing_resources
      task-name
      count_unique_numbers
```

Whereas when we do fast-serialize it generates following args for the pod after registration and has substitution parameters.

```
Args:
 pyflyte-fast-execute
      --additional-distribution
      {{ .remote_package_path }}
      --dest-dir
      {{ .dest_dir }}
      --
      pyflyte-execute
      --inputs
      s3://my-s3-bucket/metadata/propeller/flytectldemo-development-fc508e67e80104e31a5b/n0/data/inputs.pb
      --output-prefix
      s3://my-s3-bucket/metadata/propeller/flytectldemo-development-fc508e67e80104e31a5b/n0/data/0
      --raw-output-data-prefix
      s3://lyft-modelbuilder/cookbook/ge/fc508e67e80104e31a5b-n0-0
      --resolver
      flytekit.core.python_auto_container.default_task_resolver
      --
      task-module
      core.remote_flyte.customizing_resources
      task-name
      count_unique_numbers
```

And fail with 
```
      Message:  Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/flytekit/interfaces/data/data_proxy.py", line 129, in get_data
    proxy.download(remote_path, local_path)
  File "/opt/venv/lib/python3.8/site-packages/flytekit/interfaces/data/local/local_file_proxy.py", line 56, in download
    _copyfile(strip_file_header(from_path), strip_file_header(to_path))
  File "/usr/local/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '{{ .remote_package_path }}'
```

Should   {{ .remote_package_path }}  and   {{ .dest_dir }} be substituted with config values during registration in flytectl.

cc : @wild-endeavor 

**Provide a possible output or ux example**
A clear and concise description of what you want to happen or achieve.

**Comment by pmahindrakar-oss** [comment]
@kumare3 @wild-endeavor Please take a look when you get a chance on how we should be resolving this.

**Comment by kumare3** [comment]
@katrogan Did we discuss this?

**Comment by katrogan** [comment]
@kumare3 @pmahindrakar-oss if we want to mimic existing flyte-cli behavior (and have fast register work :) ) then it makes sense to substitute the `{{ .remote_package_path }}` and `{{ .dest_dir }}` args during fast registration

**Comment by pmahindrakar-oss** [comment]
Cool Thanks @katrogan .
